/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include "lucidaservice_types.h"
#include <thrift/lib/cpp2/protocol/Protocol.h>
namespace cpp2 {

struct lucidaservice_constants {};

class __attribute__((__deprecated__("lucidaserviceConstants suffers from the 'static initialization order fiasco' (https://isocpp.org/wiki/faq/ctors#static-init-order) and may CRASH you program. Instead, use lucidaservice_constants::CONSTANT_NAME()"))) lucidaserviceConstants {
 public:
  lucidaserviceConstants() {}
};

} // cpp2