language: cpp

compiler: gcc

cache: apt

sudo: true

dist: trusty

env:
    - thrift=~/thrift-0.9.2
    # - WITH_SUITE=true WITH_APP=false WITH_CUDA=false
    # - WITH_SUITE=false WITH_APP=true WITH_CUDA=false

before_install:
    - export NUM_THREADS=4
    - sudo apt-get install -y python-software-properties;
      sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
      sudo apt-get update;
      sudo apt-get install -y gcc-4.8 g++-4.8;
      sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50;
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50;
      git clone https://github.com/Itseez/opencv.git;
      cd opencv;
      git checkout 2.4.9;
      mkdir build;
      cd build;
      cmake ..;
      make -j$NUM_THREADS;
      sudo make -j$NUM_THREADS install;
      cd ../..;

install:
      travis_wait sudo -E ./travis-scripts/suite_deps.sh;
      travis_wait sudo -E ./travis-scripts/get-thrift.sh;

before_script:
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64:/usr/lib
    - export PATH=/home/travis/miniconda/bin:$PATH

script:
      cd lucida/asr/common/scripts && sudo -E ./prepare.sh && ./compile-kaldi.sh && cd -;
      cd lucida/qa/lucida && ./compile-qa.sh && cd -;
