CXX      = g++
CXXFLAGS += -I/usr/local/include -I/usr/include/atlas -std=c++11 -O3 \
            $(CUDA_INCLUDE)

LDFLAGS  += -L/usr/local/lib \
            -lstdc++ -lgflags -lglog -lthrift -lthriftcpp2 \
						-lthriftprotocol -lpthread -levent -lfolly \
             $(CUDA_LDFLAGS)
						

#-lthriftprotocol -lpthread -levent -lfolly `pkg-config --cflags --libs opencv` \
#-L/home/xiaoweiw/tools/fbthrift/thrift/lib/cpp2/.libs \
