VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.ssh.insert_key = false
    config.ssh.forward_agent = true
    
    config.vm.define "sirius" do |machine|
        machine.vm.hostname = "sirus"
        machine.vm.synced_folder "../", "/home/sirius"
    
        machine.vm.provider "virtualbox" do |v|
            v.name = "Sirius VM"
            v.customize [
                "modifyvm", :id,
                "--memory", "1024",
                "--cpus", "1"
            ]
        end

        machine.vm.provision "shell", path: "scripts/install.sh"
    end
end
