apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: imm
  name: imm-controller
spec:
  replicas: 1
  selector:
    name: imm
  template:
    metadata:
      labels:
        name: imm
    spec:
      containers:
      - image: czx5049/lucida_services:v1.2
        command: ['/bin/sh', '-c']
        args: ['cd $LUCIDAROOT/imagematching/opencv_imm/ && make start_server port=8082']
        name: imm
        ports:
        - containerPort: 8082
          name: thrift
