apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ms
  name: ms-controller
spec:
  replicas: 1
  selector:
    name: ms
  template:
    metadata:
      labels:
        name: ms
    spec:
      containers:
      - image: czx5049/lucida_services:v1.2
        command: ['/bin/sh', '-c']
        args: ['cd $LUCIDAROOT/musicservice/ && make start_server port=8089']
        name: ms
        ports:
        - containerPort: 8089
          name: thrift
