apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: we
  name: we-controller
spec:
  replicas: 1
  selector:
    name: we
  template:
    metadata:
      labels:
        name: we
    spec:
      containers:
      - image: czx5049/lucida_services:v1.2
        command: ['/bin/sh', '-c']
        args: ['cd $LUCIDAROOT/weather/ && make start_server port=8088']
        name: we
        ports:
        - containerPort: 8088
          name: thrift
