acmod.c
WORDS_BIGENDIAN
MPX_BITVEC_SET
NONMPX_BITVEC_SET
const arg_t feat_defn[][]
static int32 acmod_process_mfcbuf(acmod_t *acmod)
Process MFCCs that are in the internal buffer into features.
static int acmod_init_am(acmod_t *acmod)
static int acmod_init_feat(acmod_t *acmod)
int acmod_fe_mismatch(acmod_t *acmod, fe_t *fe)
int acmod_feat_mismatch(acmod_t *acmod, feat_t *fcb)
acmod_t* acmod_init(cmd_ln_t *config, logmath_t *lmath, fe_t *fe, feat_t *fcb)
Initialize an acoustic model.
config a command-line object containing parameters. This pointer is not retained by this object. lmath global log-math parameters. fe a previously-initialized acoustic feature module to use, or NULL to create one automatically. If this is supplied and its parameters do not match those in the acoustic model, this function will fail. This pointer is not retained. fe a previously-initialized dynamic feature module to use, or NULL to create one automatically. If this is supplied and its parameters do not match those in the acoustic model, this function will fail. This pointer is not retained. a newly initialized acmod_t, or NULL on failure.
References acmod_free, ACMOD_IDLE, acmod_s::compallsen, acmod_s::config, acmod_s::fcb, acmod_s::fe, acmod_s::feat_buf, acmod_s::framepos, acmod_s::lmath, acmod_s::log_zero, acmod_s::mdef, acmod_s::mfc_buf, acmod_s::n_feat_alloc, acmod_s::n_mfc_alloc, acmod_s::senone_active, acmod_s::senone_active_vec, acmod_s::senone_scores, acmod_s::state.
Referenced by ps_reinit.
void acmod_free(acmod_t *acmod)
Finalize an acoustic model.
References acmod_s::fcb, acmod_s::fe, acmod_s::config, acmod_s::mfc_buf, acmod_s::feat_buf, acmod_s::mfcfh, acmod_s::rawfh, acmod_s::senfh, acmod_s::framepos, acmod_s::senone_scores, acmod_s::senone_active_vec, acmod_s::senone_active, acmod_s::mdef, bin_mdef_free, acmod_s::tmat, tmat_free, acmod_s::mgau, acmod_s::mllr, ps_mllr_free.
Referenced by acmod_init, ps_reinit, ps_free.
ps_mllr_t* acmod_update_mllr(acmod_t *acmod, ps_mllr_t *mllr)
Adapt acoustic model using a linear transform.
mllr The new transform to use, or NULL to update the existing transform. The decoder retains ownership of this pointer, so you should not attempt to free it manually. Use ps_mllr_retain() if you wish to reuse it elsewhere. The updated transform object for this decoder, or NULL on failure.
References acmod_s::mgau, acmod_s::mllr, ps_mllr_free.
Referenced by ps_update_mllr.
int acmod_write_senfh_header(acmod_t *acmod, FILE *logfh)
Write senone dump file header.
References acmod_s::mdef, acmod_s::lmath, acmod_s::config.
Referenced by acmod_set_senfh.
int acmod_set_senfh(acmod_t *acmod, FILE *logfh)
Start logging senone scores to a filehandle.
acmod Acoustic model object. logfh Filehandle to log to. 0 for success, <0 on error.
References acmod_write_senfh_header, acmod_s::senfh.
Referenced by ps_start_utt.
int acmod_set_mfcfh(acmod_t *acmod, FILE *logfh)
Start logging MFCCs to a filehandle.
acmod Acoustic model object. logfh Filehandle to log to. 0 for success, <0 on error.
References acmod_s::mfcfh.
Referenced by ps_start_utt.
int acmod_set_rawfh(acmod_t *acmod, FILE *logfh)
Start logging raw audio to a filehandle.
acmod Acoustic model object. logfh Filehandle to log to. 0 for success, <0 on error.
References acmod_s::rawfh.
Referenced by ps_start_utt.
void acmod_grow_feat_buf(acmod_t *acmod, int nfr)
int acmod_set_grow(acmod_t *acmod, int grow_feat)
Set memory allocation policy for utterance processing.
grow_feat If non-zero, the internal dynamic feature buffer will expand as necessary to encompass any amount of data fed to the model. previous allocation policy.
References acmod_s::grow_feat, acmod_s::n_feat_alloc.
Referenced by ngram_search_init, ps_process_raw.
int acmod_start_utt(acmod_t *acmod)
Mark the start of an utterance.
References acmod_s::fe, acmod_s::state, ACMOD_STARTED, acmod_s::n_mfc_frame, acmod_s::n_feat_frame, acmod_s::mfc_outidx, acmod_s::feat_outidx, acmod_s::output_frame, acmod_s::senscr_frame, acmod_s::n_senone_active, acmod_s::mgau, ps_mgau_s::frame_idx.
Referenced by ps_start_utt.
int acmod_end_utt(acmod_t *acmod)
Mark the end of an utterance.
References acmod_s::state, ACMOD_ENDED, acmod_s::n_mfc_frame, acmod_s::n_mfc_alloc, acmod_s::mfc_outidx, acmod_s::fe, acmod_s::mfc_buf, acmod_s::mfcfh, acmod_s::rawfh, acmod_s::senfh.
Referenced by ps_end_utt.
static int acmod_log_mfc(acmod_t *acmod, mfcc_t **cep, int n_frames)
static int acmod_process_full_cep(acmod_t *acmod, mfcc_t ***inout_cep, int *inout_n_frames)
static int acmod_process_full_raw(acmod_t *acmod, int16 const **inout_raw, size_t *inout_n_samps)
int acmod_process_raw(acmod_t *acmod, int16 const **inout_raw, size_t *inout_n_samps, int full_utt)
TODO: Set queue length for utterance processing.
This function allows multiple concurrent passes of search to operate on different parts of the utterance. Feed raw audio data to the acoustic model for scoring. inout_raw In: Pointer to buffer of raw samples Out: Pointer to next sample to be read inout_n_samps In: Number of samples available Out: Number of samples remaining full_utt If non-zero, this block represents a full utterance and should be processed as such. Number of frames of data processed.
References acmod_s::fe, acmod_s::mfc_buf, acmod_s::mfc_outidx, acmod_s::n_mfc_alloc, acmod_s::n_mfc_frame, acmod_s::rawfh.
Referenced by ps_process_raw.
int acmod_process_cep(acmod_t *acmod, mfcc_t ***inout_cep, int *inout_n_frames, int full_utt)
Feed acoustic feature data into the acoustic model for scoring.
inout_cep In: Pointer to buffer of features Out: Pointer to next frame to be read inout_n_frames In: Number of frames available Out: Number of frames remaining full_utt If non-zero, this block represents a full utterance and should be processed as such. Number of frames of data processed.
References ACMOD_ENDED, ACMOD_PROCESSING, ACMOD_STARTED, acmod_s::fcb, acmod_s::feat_buf, acmod_s::feat_outidx, acmod_s::grow_feat, acmod_s::mfcfh, acmod_s::n_feat_alloc, acmod_s::n_feat_frame, acmod_s::state.
int acmod_process_feat(acmod_t *acmod, mfcc_t **feat)
Feed dynamic feature data into the acoustic model for scoring.
Unlike acmod_process_raw() and acmod_process_cep(), this function accepts a single frame at a time. This is because there is no need to do buffering when using dynamic features as input. However, if the dynamic feature buffer is full, this function will fail, so you should either always check the return value, or always pair a call to it with a call to acmod_score(). feat Pointer to one frame of dynamic features. Number of frames processed (either 0 or 1).
References acmod_s::fcb, acmod_s::feat_buf, acmod_s::feat_outidx, acmod_s::grow_feat, acmod_s::n_feat_alloc, acmod_s::n_feat_frame.
static int acmod_read_senfh_header(acmod_t *acmod)
int acmod_set_insenfh(acmod_t *acmod, FILE *senfh)
Set up a senone score dump file for input.
insenfh File handle of dump file 0 for success, <0 for failure
References acmod_s::compallsen, acmod_s::config, acmod_s::insenfh, acmod_s::n_feat_frame.
Referenced by ps_decode_senscr.
int acmod_rewind(acmod_t *acmod)
Rewind the current utterance, allowing it to be rescored.
After calling this function, the internal frame index is reset, and acmod_score() will return scores starting at the first frame of the current utterance. Currently, acmod_set_grow() must have been called to enable growing the feature buffer in order for this to work. In the future, senone scores may be cached instead.0 for success, <0 for failure (if the utterance can't be rewound due to no feature or score data available)
References acmod_s::feat_outidx, ps_mgau_s::frame_idx, acmod_s::mgau, acmod_s::n_feat_alloc, acmod_s::n_feat_frame, acmod_s::output_frame, acmod_s::senscr_frame.
int acmod_advance(acmod_t *acmod)
Advance the frame index.
This function moves to the next frame of input data. Subsequent calls to acmod_score() will return scores for that frame, until the next call to acmod_advance().New frame index.
References acmod_s::feat_outidx, ps_mgau_s::frame_idx, acmod_s::mgau, acmod_s::n_feat_alloc, acmod_s::n_feat_frame, acmod_s::output_frame.
int acmod_write_scores(acmod_t *acmod, int n_active, uint8 const *active, int16 const *senscr, FILE *senfh)
Write a frame of senone scores to a dump file.
References acmod_s::mdef.
Referenced by acmod_score.
static int acmod_read_scores_internal(acmod_t *acmod)
Internal version, used for reading previous frames in acmod_score()
int acmod_read_scores(acmod_t *acmod)
Read one frame of scores from senone score dump file.
Number of frames read or <0 on error.
References acmod_s::feat_outidx, acmod_s::framepos, acmod_s::grow_feat, acmod_s::insenfh, acmod_s::n_feat_alloc, acmod_s::n_feat_frame, acmod_s::n_senone_active, acmod_s::output_frame, acmod_s::senscr_frame.
Referenced by ps_decode_senscr.
static int calc_frame_idx(acmod_t *acmod, int *inout_frame_idx)
static int calc_feat_idx(acmod_t *acmod, int frame_idx)
mfcc_t** acmod_get_frame(acmod_t *acmod, int *inout_frame_idx)
Get a frame of dynamic feature data.
inout_frame_idx Input: frame index to get, or NULL to obtain features for the most recent frame. Output: frame index corresponding to this set of features. Feature array, or NULL if requested frame is not available.
References acmod_s::feat_buf.
int16 const* acmod_score(acmod_t *acmod, int *inout_frame_idx)
Score one frame of data.
inout_frame_idx Input: frame index to score, or NULL to obtain scores for the most recent frame. Output: frame index corresponding to this set of scores. Array of senone scores for this frame, or NULL if no frame is available for scoring (such as if a frame index is requested that is not yet or no longer available). The data pointed to persists only until the next call to acmod_score() or acmod_advance().
References acmod_flags2list, acmod_write_scores, acmod_s::compallsen, acmod_s::feat_buf, acmod_s::framepos, acmod_s::insenfh, acmod_s::mgau, acmod_s::n_senone_active, acmod_s::senfh, acmod_s::senone_active, acmod_s::senone_scores, acmod_s::senscr_frame.
Referenced by ngram_fwdflat_search, ngram_fwdtree_search.
int acmod_best_score(acmod_t *acmod, int *out_best_senid)
Get best score and senone index for current frame.
References SENSCR_DUMMY, acmod_s::compallsen, acmod_s::mdef, acmod_s::senone_scores, acmod_s::n_senone_active, acmod_s::senone_active.
void acmod_clear_active(acmod_t *acmod)
Clear set of active senones.
References acmod_s::compallsen, acmod_s::senone_active_vec, acmod_s::mdef, acmod_s::n_senone_active.
void acmod_activate_hmm(acmod_t *acmod, hmm_t *hmm)
Activate senones associated with an HMM.
References acmod_s::compallsen.
int32 acmod_flags2list(acmod_t *acmod)
Build active list from.
References ps_mllr_s::b, acmod_s::mdef, acmod_s::compallsen, acmod_s::n_senone_active, acmod_s::senone_active_vec, acmod_s::senone_active, acmod_s::output_frame.
Referenced by acmod_score.