bin_mdef.c
FREAD_SWAP32_CHK
const char format_desc[][]
bin_mdef_t* bin_mdef_read_text(cmd_ln_t *config, const char *filename)
Read a text mdef from a file (creating an in-memory binary mdef).
References acmod_s::mdef, mdef_init, mdef_t::n_sen, BAD_SENID, mdef_free, mdef_t::n_sseq, BAD_SSID, mdef_t::n_ciphone, bin_mdef_s::n_ciphone, bin_mdef_s::n_phone, mdef_t::n_phone, bin_mdef_s::n_emit_state, mdef_t::n_emit_state, bin_mdef_s::n_ci_sen, mdef_t::n_ci_sen, bin_mdef_s::n_sen, bin_mdef_s::n_tmat, mdef_t::n_tmat, bin_mdef_s::n_sseq, bin_mdef_s::sseq, mdef_t::sseq, bin_mdef_s::cd2cisen, mdef_t::cd2cisen, bin_mdef_s::sen2cimap, mdef_t::sen2cimap, bin_mdef_s::n_ctx, bin_mdef_s::sil, mdef_t::sil, bin_mdef_s::ciname, mdef_t::ciphone, ciphone_t::name, bin_mdef_free, bin_mdef_s::phone, mdef_entry_s::ssid, mdef_t::phone, phone_t::ssid, mdef_entry_s::tmat, phone_t::tmat, mdef_entry_s::ci, ciphone_t::filler, phone_t::wpos, phone_t::rc, N_WORD_POSN, mdef_t::wpos_ci_lclist, bin_mdef_s::cd_tree, bin_mdef_s::n_cd_tree, cd_tree_s::ctx, cd_tree_s::n_down, cd_tree_s::down, WPOS_NAME, cd_tree_s::pid, bin_mdef_s::alloc_mode.
Referenced by bin_mdef_read.
bin_mdef_t* bin_mdef_retain(bin_mdef_t *m)
Retain a pointer to a bin_mdef_t.
Referenced by dict_init, dict2pid_build.
int bin_mdef_free(bin_mdef_t *m)
Release a pointer to a binary mdef.
References bin_mdef_s::alloc_mode, bin_mdef_s::ciname, bin_mdef_s::sseq, bin_mdef_s::phone, bin_mdef_s::cd_tree, bin_mdef_s::filemap, bin_mdef_s::cd2cisen, bin_mdef_s::sen2cimap.
Referenced by acmod_free, bin_mdef_read_text, dict_free, dict2pid_free.
bin_mdef_t* bin_mdef_read(cmd_ln_t *config, const char *filename)
Read a binary mdef from a file.
References bin_mdef_read_text, bin_mdef_s::n_ciphone, bin_mdef_s::n_phone, bin_mdef_s::n_emit_state, bin_mdef_s::n_ci_sen, bin_mdef_s::n_sen, bin_mdef_s::n_tmat, bin_mdef_s::n_sseq, bin_mdef_s::n_ctx, bin_mdef_s::n_cd_tree, bin_mdef_s::sil, bin_mdef_s::ciname, bin_mdef_s::filemap, bin_mdef_s::alloc_mode, bin_mdef_s::cd_tree, cd_tree_s::ctx, cd_tree_s::n_down, cd_tree_s::down, bin_mdef_s::phone, mdef_entry_s::ssid, mdef_entry_s::tmat, bin_mdef_s::sseq, bin_mdef_s::sseq_len, bin_mdef_s::cd2cisen, bin_mdef_s::sen2cimap, bin_mdef_ciphone_id, S3_SILENCE_CIPHONE.
int bin_mdef_write(bin_mdef_t *m, const char *filename)
Write a binary mdef to a file.
References bin_mdef_s::n_ciphone, bin_mdef_s::n_phone, bin_mdef_s::n_emit_state, bin_mdef_s::n_ci_sen, bin_mdef_s::n_sen, bin_mdef_s::n_tmat, bin_mdef_s::n_sseq, bin_mdef_s::n_ctx, bin_mdef_s::n_cd_tree, bin_mdef_s::sil, bin_mdef_s::ciname, bin_mdef_s::cd_tree, bin_mdef_s::phone, bin_mdef_s::sseq, bin_mdef_s::sseq_len.
int bin_mdef_write_text(bin_mdef_t *m, const char *filename)
Write a binary mdef to a text file.
References bin_mdef_s::n_ciphone, bin_mdef_s::n_phone, bin_mdef_s::n_emit_state, bin_mdef_s::sseq_len, bin_mdef_s::phone, mdef_entry_s::ssid, bin_mdef_s::n_sen, bin_mdef_s::n_ci_sen, bin_mdef_s::n_tmat, bin_mdef_s::ciname, mdef_entry_s::tmat, bin_mdef_s::sseq, WPOS_NAME.
int bin_mdef_ciphone_id(bin_mdef_t *m, const char *ciphone)
In: Model structure being queried
phone id for ciphone.In: ciphone for which id wanted
References bin_mdef_s::n_ciphone, bin_mdef_s::ciname.
Referenced by bin_mdef_read, ps_add_word.
int bin_mdef_ciphone_id_nocase(bin_mdef_t *m, const char *ciphone)
In: Model structure being queried
phone id for ciphone.In: ciphone for which id wanted
References bin_mdef_s::n_ciphone, bin_mdef_s::ciname.
const char* bin_mdef_ciphone_str(bin_mdef_t *m, int32 ci)
In: Model structure being queried
References bin_mdef_s::ciname.
Referenced by bin_mdef_phone_str, dict_ciphone_str, dict2pid_add_word, dict2pid_build, dict2pid_dump.
int bin_mdef_phone_id(bin_mdef_t *m, int32 ci, int32 lc, int32 rc, int32 wpos)
In: Model structure being queried
References N_WORD_POSN, bin_mdef_s::sil, bin_mdef_s::phone, mdef_entry_s::ci, bin_mdef_s::cd_tree, bin_mdef_s::ciname, cd_tree_s::ctx, cd_tree_s::n_down, cd_tree_s::down, cd_tree_s::pid.
int bin_mdef_phone_id_nearest(bin_mdef_t *m, int32 b, int32 l, int32 r, int32 pos)
int bin_mdef_phone_str(bin_mdef_t *m, int pid, char *buf)
In: Model structure being queried
0 if successful, -1 if error.Out: On return, buf has the string
References WPOS_NAME, bin_mdef_ciphone_str, bin_mdef_s::phone.