dict.c
DELIM
DEFAULT_NUM_PHONE
const char* const cmu6_lts_phone_table[][]
static s3cipid_t dict_ciphone_id(dict_t *d, const char *str)
const char* dict_ciphone_str(dict_t *d, s3wid_t wid, int32 pos)
In: Dictionary to look up
References bin_mdef_ciphone_str, dict_t::mdef, dict_t::word, dictword_t::ciphone.
Referenced by dict_write.
s3wid_t dict_add_word(dict_t *d, char const *word, s3cipid_t const *p, int32 np)
The dictionary structure.
Return value: Result word id if successful, BAD_S3WID otherwise
References dict_t::n_word, dict_t::max_words, dict_t::word, dictword_t::word, dict_word2basestr, dict_t::ht, BAD_S3WID, dictword_t::basewid, dictword_t::alt, dictword_t::ciphone, dictword_t::pronlen.
Referenced by dict_init, ps_add_word, ps_lattice_read.
static int32 dict_read(FILE *fp, dict_t *d)
int dict_write(dict_t *dict, char const *filename, char const *format)
Write dictionary to a file.
References dict_t::n_word, dict_real_word, dict_ciphone_str.
Referenced by ps_save_dict.
dict_t* dict_init(cmd_ln_t *config, bin_mdef_t *mdef)
Configuration (-dict, -fdict, -dictcase) or NULL
If config and mdef are supplied, then the dictionary will be read from the files specified by the -dict and -fdict options in config, with case sensitivity determined by the -dictcase option.Otherwise an empty case-sensitive dictionary will be created.Return ptr to dict_t if successful, NULL otherwise.
References dict_t::max_words, dict_t::word, dict_t::n_word, dict_t::mdef, bin_mdef_retain, dict_t::ht, dict_t::filler_start, dict_wordid, BAD_S3WID, dict_add_word, dict_t::filler_end, dict_t::startwid, dict_t::finishwid, dict_t::silwid, dict_filler_word, dict_free.
Referenced by ps_reinit, ps_load_dict, ps_lattice_read.
s3wid_t dict_wordid(dict_t *d, const char *word)
Return word id for given word string if present.
Otherwise return BAD_S3WID
References dict_t::ht, BAD_S3WID.
Referenced by dict_init, ps_nbest, ps_lattice_read.
int dict_filler_word(dict_t *d, s3wid_t w)
The dictionary structure
A filler word is one that was read in from the filler dictionary; however, sentence START and FINISH words are not filler words.
References dict_t::startwid, dict_t::finishwid, dict_t::filler_start.
Referenced by dict_init, ngram_search_lattice, ps_lattice_bypass_fillers, ps_lattice_write_htk, ps_lattice_read, ps_lattice_bestpath, ps_lattice_posterior.
int dict_real_word(dict_t *d, s3wid_t w)
The dictionary structure
neither a filler word nor START/FINISH.
References dict_t::startwid, dict_t::finishwid, dict_t::filler_start.
Referenced by dict_write, ngram_search_bp_hyp, ps_lattice_hyp, ps_astar_hyp.
int32 dict_word2basestr(char *word)
If the given word contains a trailing "(....)" (i.e., a Sphinx-II style alternative pronunciation specification), strip that trailing portion from it.
Note that the given string is modified. Return value: If string was modified, the character position at which the original string was truncated; otherwise -1.
Referenced by dict_add_word, ps_lattice_read.
dict_t* dict_retain(dict_t *d)
Retain a pointer to an dict_t.
Referenced by dict2pid_build, ps_search_init, ps_search_base_reinit, ps_lattice_read, ps_lattice_init_search.
int dict_free(dict_t *d)
Release a pointer to a dictionary.
References dict_t::n_word, dict_t::word, dictword_t::word, dictword_t::ciphone, dict_t::ht, dict_t::mdef, bin_mdef_free.
Referenced by dict_init, dict2pid_free, ps_reinit, ps_free, ps_load_dict, ps_search_base_reinit, ps_search_deinit, ps_lattice_free.
void dict_report(dict_t *d)
A dictionary structure
References dict_t::max_words, dict_t::n_word.