dict2pid.c
void compress_table(s3ssid_t *uncomp_tab, s3ssid_t *com_tab, s3cipid_t *ci_map, int32 n_ci)
References BAD_S3CIPID, BAD_S3SSID.
Referenced by dict2pid_add_word.
static void compress_right_context_tree(dict2pid_t *d2p, s3ssid_t ***rdiph_rc)
static void compress_left_right_context_tree(dict2pid_t *d2p)
int32 get_rc_nssid(dict2pid_t *d2p, s3wid_t w)
In: a dict2pid
Get number of rc.I doubt whether it is correct because the compressed map has not been checked.
References dictword_t::ciphone, dict2pid_t::dict, dict2pid_t::lrssid, xwdssid_t::n_ssid, dictword_t::pronlen, dict2pid_t::rssid, dict_t::word.
s3cipid_t* dict2pid_get_rcmap(dict2pid_t *d2p, s3wid_t w)
In: a dict2pid
References xwdssid_t::cimap, dictword_t::ciphone, dict2pid_t::dict, dict2pid_t::lrssid, dictword_t::pronlen, dict2pid_t::rssid, dict_t::word.
static void free_compress_map(xwdssid_t **tree, int32 n_ci)
static void populate_lrdiph(dict2pid_t *d2p, s3ssid_t ***rdiph_rc, s3cipid_t b)
int dict2pid_add_word(dict2pid_t *d2p, int32 wid)
Add a word to the dict2pid structure (after adding it to dict).
References dict2pid_t::mdef, dict2pid_t::dict, dict2pid_t::ldiph_lc, BAD_S3SSID, bin_mdef_ciphone_str, WORD_POSN_BEGIN, dict2pid_t::rssid, WORD_POSN_END, compress_table, bin_mdef_s::n_ciphone, xwdssid_t::ssid, xwdssid_t::cimap, xwdssid_t::n_ssid, dict2pid_t::lrdiph_rc.
Referenced by ps_add_word.
s3ssid_t dict2pid_internal(dict2pid_t *d2p, int32 wid, int pos)
Return the senone sequence ID for the given word position.
References dict2pid_t::dict, dict2pid_t::mdef, BAD_S3SSID, dict_pron, WORD_POSN_INTERNAL.
Referenced by dict2pid_dump, ps_alignment_populate.
dict2pid_t* dict2pid_build(bin_mdef_t *mdef, dict_t *dict)
A model definition
References BAD_S3SSID, bin_mdef_ciphone_str, bin_mdef_retain, dict2pid_t::dict, dict2pid_report, dict_pron, dict_retain, dict_size, dict2pid_t::ldiph_lc, dict2pid_t::lrdiph_rc, dict2pid_t::mdef, bin_mdef_s::n_ciphone, WORD_POSN_BEGIN, WORD_POSN_END.
Referenced by ps_load_dict, ps_reinit.
dict2pid_t* dict2pid_retain(dict2pid_t *d2p)
Retain a pointer to dict2pid.
Referenced by ps_search_init, ps_search_base_reinit, ps_alignment_init.
int dict2pid_free(dict2pid_t *d2p)
In: the d2p
References bin_mdef_free, dict2pid_t::dict, dict_free, dict2pid_t::ldiph_lc, dict2pid_t::lrdiph_rc, dict2pid_t::lrssid, dict2pid_t::mdef, dict2pid_t::rssid.
Referenced by ps_alignment_free, ps_free, ps_load_dict, ps_reinit, ps_search_base_reinit, ps_search_deinit.
void dict2pid_report(dict2pid_t *d2p)
In: a dict2pid_t structure
Referenced by dict2pid_build.
void dict2pid_dump(FILE *fp, dict2pid_t *d2p)
In: a file pointer
References bin_mdef_ciphone_str, dict2pid_t::dict, dict2pid_internal, dict_size, dict2pid_t::ldiph_lc, dict2pid_t::mdef, bin_mdef_s::n_sseq, bin_mdef_s::sseq.