hmm.c
hmm_tprob_5st
nonmpx_senscr
mpx_senid
mpx_senscr
hmm_tprob_3st
hmm_context_t* hmm_context_init(int32 n_emit_state, uint8 **const *tp, int16 const *senscore, uint16 *const *sseq)
Create an HMM context.
References HMM_MAX_NSTATE.
Referenced by ngram_search_init.
void hmm_context_free(hmm_context_t *ctx)
Free an HMM context.
The transition matrices, senone scores, and senone sequence mapping are all assumed to be allocated externally, and will NOT be freed by this function.
Referenced by ngram_search_free.
void hmm_init(hmm_context_t *ctx, hmm_t *hmm, int mpx, int ssid, int tmatid)
Populate a previously-allocated HMM structure, allocating internal data.
References BAD_SSID, hmm_clear.
Referenced by ngram_search_alloc_all_rc.
void hmm_deinit(hmm_t *hmm)
Free an HMM structure, releasing internal data (but not the HMM structure itself).
Referenced by ngram_search_free_all_rc.
void hmm_dump(hmm_t *hmm, FILE *fp)
In/Out: HMM being updated
Referenced by hmm_dump_vit_eval.
void hmm_clear_scores(hmm_t *h)
Reset the scores of the HMM.
References WORST_SCORE.
void hmm_clear(hmm_t *h)
Reset the states of the HMM to the invalid condition.
i.e., scores to WORST_SCORE and hist to undefined.
References WORST_SCORE.
Referenced by fsg_psubtree_pnode_deactivate, hmm_init, ngram_fwdflat_start, ngram_fwdtree_start, ngram_fwdtree_finish.
void hmm_enter(hmm_t *h, int32 score, int32 histid, int frame)
Enter an HMM with the given path score and history ID.
Referenced by ngram_fwdflat_start, ngram_fwdtree_start.
void hmm_normalize(hmm_t *h, int32 bestscr)
Renormalize the scores in this HMM based on the given best score.
References BETTER_THAN, WORST_SCORE.
static int32 hmm_vit_eval_5st_lr(hmm_t *hmm)
static int32 hmm_vit_eval_5st_lr_mpx(hmm_t *hmm)
static int32 hmm_vit_eval_3st_lr(hmm_t *hmm)
static int32 hmm_vit_eval_3st_lr_mpx(hmm_t *hmm)
static int32 hmm_vit_eval_anytopo(hmm_t *hmm)
int32 hmm_vit_eval(hmm_t *hmm)
Viterbi evaluation of given HMM.
If this module were being used for tracking state segmentations, the dummy, non-emitting exit state would have to be updated separately. In the Viterbi DP diagram, transitions to the exit state occur from the current time; they are vertical transitions. Hence they should be made only after the history has been logged for the emitting states. But we're not bothered with state segmentations, for now. So, we update the exit state as well.
Referenced by hmm_dump_vit_eval.
int32 hmm_dump_vit_eval(hmm_t *hmm, FILE *fp)
In/Out: HMM being updated
References hmm_dump, hmm_vit_eval.