mdef.c
MODEL_DEF_VERSION
static void ciphone_add(mdef_t *m, char *ci, int p)
static ph_lc_t* find_ph_lc(ph_lc_t *lclist, int lc)
static ph_rc_t* find_ph_rc(ph_rc_t *rclist, int rc)
static void triphone_add(mdef_t *m, int ci, int lc, int rc, word_posn_t wpos, int p)
int mdef_ciphone_id(mdef_t *m, char *ci)
In: Model structure being queried
ciphone id for the given ciphone string name
References mdef_t::ciphone_ht.
const char* mdef_ciphone_str(mdef_t *m, int id)
In: Model structure being queried
: READ-ONLY ciphone string name for the given ciphone id
References mdef_t::ciphone, ciphone_t::name.
Referenced by mdef_phone_str.
int mdef_phone_str(mdef_t *m, int pid, char *buf)
In: Model structure being queried
0 if successful, -1 if error.
References WPOS_NAME, mdef_ciphone_str, mdef_t::phone, phone_t::rc, phone_t::wpos.
int mdef_phone_id(mdef_t *m, int ci, int lc, int rc, word_posn_t wpos)
In: Model structure being queried
: phone id for the given constituents if found, else BAD_S3PID
References N_WORD_POSN, mdef_t::wpos_ci_lclist, mdef_t::sil, mdef_t::ciphone, ciphone_t::filler.
int mdef_is_ciphone(mdef_t *m, int p)
In: Model structure being queried
1 if given triphone argument is a ciphone, 0 if not, -1 if error
int mdef_is_cisenone(mdef_t *m, int s)
In: Model structure being queried
1 if a given senone is a ci senone
References mdef_t::n_sen, mdef_t::cd2cisen.
static void parse_tmat_senmap(mdef_t *m, char *line, int32 off, int p)
static void parse_base_line(mdef_t *m, char *line, int p)
static void parse_tri_line(mdef_t *m, char *line, int p)
static void sseq_compress(mdef_t *m)
static int32 noncomment_line(char *line, int32 size, FILE *fp)
mdef_t* mdef_init(char *mdeffile, int32 breport)
void mdef_report(mdef_t *m)
In: model definition structure
References mdef_t::n_ciphone, mdef_t::n_phone, mdef_t::n_emit_state, mdef_t::n_ci_sen, mdef_t::n_sen, mdef_t::n_sseq.
void mdef_free_recursive_lc(ph_lc_t *lc)
In: A list of left context
References mdef_free_recursive_rc.
Referenced by mdef_free.
void mdef_free_recursive_rc(ph_rc_t *rc)
In: A list of right context
Referenced by mdef_free_recursive_lc, mdef_free.
void mdef_free(mdef_t *m)
In : The model definition
References mdef_t::sen2cimap, mdef_t::cd2cisen, N_WORD_POSN, mdef_t::n_ciphone, mdef_t::wpos_ci_lclist, mdef_free_recursive_lc, mdef_free_recursive_rc, mdef_t::sseq, mdef_t::phone, mdef_t::ciphone_ht, mdef_t::ciphone, ciphone_t::name.
Referenced by bin_mdef_read_text.