ngram_search.c
NGRAM_HISTORY_LONG_WORD
ps_searchfuncs_t ngram_funcs
ngram_model_t* default_lm
ps_segfuncs_t ngram_bp_segfuncs
static int ngram_search_start(ps_search_t *search)
static int ngram_search_step(ps_search_t *search, int frame_idx)
static int ngram_search_finish(ps_search_t *search)
static int ngram_search_reinit(ps_search_t *search, dict_t *dict, dict2pid_t *d2p)
static char const * ngram_search_hyp(ps_search_t *search, int32 *out_score, int32 *out_is_final)
static int32 ngram_search_prob(ps_search_t *search)
static ps_seg_t * ngram_search_seg_iter(ps_search_t *search, int32 *out_score)
static void ngram_search_update_widmap(ngram_search_t *ngs)
static void ngram_search_calc_beams(ngram_search_t *ngs)
ps_search_t* ngram_search_init(ngram_model_t *lm, cmd_ln_t *config, acmod_t *acmod, dict_t *dict, dict2pid_t *d2p)
Initialize the N-Gram search module.
References acmod_set_grow, ps_search_init, ngram_search_s::hmmctx, hmm_context_init, acmod_s::mdef, acmod_s::tmat, tmat_t::tp, bin_mdef_s::sseq, ngram_search_s::chan_alloc, ngram_search_s::root_chan_alloc, ngram_search_s::latnode_alloc, ngram_search_s::word_chan, dict_size, ngram_search_s::word_active, ngram_search_s::n_frame_alloc, ngram_search_s::active_word_list, ngram_search_s::lmset, ngram_fwdtree_init, ngram_fwdflat_init, ngram_search_free.
Referenced by ps_set_lm.
void ngram_search_free(ps_search_t *search)
Finalize the N-Gram search module.
References ps_search_deinit, ngram_fwdtree_deinit, ngram_fwdflat_deinit, hmm_context_free, ngram_search_s::hmmctx, ngram_search_s::chan_alloc, ngram_search_s::root_chan_alloc, ngram_search_s::latnode_alloc, ngram_search_s::lmset, ngram_search_s::word_chan, ngram_search_s::word_active, ngram_search_s::active_word_list.
Referenced by ngram_search_init.
int ngram_search_mark_bptable(ngram_search_t *ngs, int frame_idx)
Record the current frame's index in the backpointer table.
the current backpointer index.
References ngram_search_s::frm_wordlist, ngram_search_s::n_frame_alloc.
Referenced by ngram_fwdflat_finish, ngram_fwdflat_search, ngram_fwdtree_finish, ngram_fwdtree_search.
static void set_real_wid(ngram_search_t *ngs, int32 bp)
void ngram_search_save_bp(ngram_search_t *ngs, int frame_idx, int32 w, int32 score, int32 path, int32 rc)
Enter a word in the backpointer table.
References bptbl_s::frame, bptbl_s::score, WORSE_THAN, bptbl_s::bp, bptbl_s::prev_real_wid, bptbl_s::real_wid, bptbl_s::s_idx, bptbl_s::wid, bptbl_s::valid, bptbl_s::last_phone, bptbl_s::last2_phone, dict2pid_rssid, WORST_SCORE.
int ngram_search_find_exit(ngram_search_t *ngs, int frame_idx, int32 *out_best_score, int32 *out_is_final)
Find the best word exit for the current frame in the backpointer table.
the backpointer index of the best word exit.
References BETTER_THAN, ngram_search_s::n_frame, bptbl_s::score, bptbl_s::wid, WORST_SCORE.
char const* ngram_search_bp_hyp(ngram_search_t *ngs, int bpidx)
Backtrace from a given backpointer index to obtain a word hypothesis.
a read-only string with the best hypothesis.
References bptbl_s::bp, dict_real_word, ps_search_s::hyp_str, bptbl_s::wid.
void ngram_search_alloc_all_rc(ngram_search_t *ngs, int32 w)
Allocate last phone channels for all possible right contexts for word w.
References dict2pid_rssid, ngram_search_s::word_chan, chan_s::hmm, xwdssid_t::ssid, ngram_search_s::chan_alloc, chan_s::next, chan_s::rc_id, chan_s::ciphone, hmm_init, ngram_search_s::hmmctx, xwdssid_t::n_ssid.
void ngram_search_free_all_rc(ngram_search_t *ngs, int32 w)
Allocate last phone channels for all possible right contexts for word w.
References ngram_search_s::word_chan, chan_s::next, hmm_deinit, chan_s::hmm, ngram_search_s::chan_alloc.
Referenced by ngram_fwdtree_finish.
int32 ngram_search_exit_score(ngram_search_t *ngs, bptbl_t *pbe, int rcphone)
Get the exit score for a backpointer entry with a given right context.
References bptbl_s::last2_phone, bptbl_s::score, dict2pid_rssid, bptbl_s::last_phone, bptbl_s::s_idx, xwdssid_t::cimap.
Referenced by ngram_search_lattice.
void ngram_compute_seg_score(ngram_search_t *ngs, bptbl_t *be, float32 lwf, int32 *out_ascr, int32 *out_lscr)
void dump_bptable(ngram_search_t *ngs)
static ps_latlink_t* ngram_search_bestpath(ps_search_t *search, int32 *out_score, int backward)
static void ngram_search_bp2itor(ps_seg_t *seg, int bp)
static void ngram_bp_seg_free(ps_seg_t *seg)
static ps_seg_t* ngram_bp_seg_next(ps_seg_t *seg)
static ps_seg_t* ngram_search_bp_iter(ngram_search_t *ngs, int bpidx, float32 lwf)
static void create_dag_nodes(ngram_search_t *ngs, ps_lattice_t *dag)
static ps_latnode_t* find_start_node(ngram_search_t *ngs, ps_lattice_t *dag)
static ps_latnode_t* find_end_node(ngram_search_t *ngs, ps_lattice_t *dag, float32 lwf)
ps_lattice_t* ngram_search_lattice(ps_search_t *search)
Construct a word lattice from the current hypothesis.
References ngram_search_s::best_score, WORST_SCORE, WORSE_THAN, ps_search_s::dag, ps_lattice_s::n_frames, ngram_search_s::n_frame, ps_lattice_free, ps_lattice_init_search, ps_lattice_s::start, ps_lattice_s::end, ps_search_s::dict, ps_latnode_s::wid, ps_latnode_s::sf, ps_latnode_s::lef, ps_lattice_s::final_node_ascr, ps_lattice_s::nodes, ps_latnode_s::next, ps_lattice_s::latnode_alloc, ps_latnode_s::reachable, ps_latnode_s::fef, bptbl_s::frame, bptbl_s::wid, ngram_search_exit_score, bptbl_s::score, BETTER_THAN, ps_lattice_link, ps_latnode_s::basewid, ps_latnode_s::alt, ps_lattice_s::n_nodes, dict_filler_word, ps_lattice_delete_unreachable, ps_lattice_bypass_fillers.
void ngram_search_set_lm(ngram_model_t *lm)
Sets the global language model.
Sets the language model to use if nothing was passed in configuration