pocketsphinx.c
const arg_t ps_args_def[][]
static int file_exists(const char *path)
static int hmmdir_exists(const char *path)
static void ps_add_file(ps_decoder_t *ps, const char *arg, const char *hmmdir, const char *file)
static void ps_init_defaults(ps_decoder_t *ps)
static void ps_free_searches(ps_decoder_t *ps)
static ps_search_t* ps_find_search(ps_decoder_t *ps, char const *name)
void ps_default_search_args(cmd_ln_t *config)
Sets default grammar and language model if they are not set explicitly and are present in the default search path.
int ps_reinit(ps_decoder_t *ps, cmd_ln_t *config)
Reinitialize the decoder with updated configuration.
This function allows you to switch the acoustic model, dictionary, or other configuration without creating an entirely new decoding object.The decoder retains ownership of the pointer config, so you must not attempt to free it manually. If you wish to reuse it elsewhere, call cmd_ln_retain() on it. ps Decoder. config An optional new configuration to use. If this is NULL, the previous configuration will be reloaded, with any changes applied. 0 for success, <0 for failure.
References ps_decoder_s::config, ps_decoder_s::mfclogdir, ps_decoder_s::rawlogdir, ps_decoder_s::senlogdir, ps_decoder_s::searches, acmod_free, ps_decoder_s::acmod, dict_free, ps_decoder_s::dict, dict2pid_free, ps_decoder_s::d2p, ps_decoder_s::lmath, acmod_init, ps_decoder_s::pl_window, ps_decoder_s::phone_loop, dict_init, acmod_s::mdef, dict2pid_build, ps_set_keyphrase, ps_set_search, ps_set_kws, ps_set_fsg, ps_set_jsgf_file, ps_set_lm_file, ps_set_lm, ps_decoder_s::perf.
Referenced by ps_init.
ps_decoder_t* ps_init(cmd_ln_t *config)
Initialize the decoder from a configuration object.
The decoder retains ownership of the pointer config, so you must not attempt to free it manually. If you wish to reuse it elsewhere, call cmd_ln_retain() on it. config a command-line structure, as created by cmd_ln_parse_r() or cmd_ln_parse_file_r().
References ps_decoder_s::refcount, ps_reinit, ps_free.
arg_t const* ps_args(void)
Returns the argument definitions used in ps_init().
This is here to avoid exporting global data, which is problematic on Win32 and Symbian (and possibly other platforms).
Referenced by ps_load_dict.
ps_decoder_t* ps_retain(ps_decoder_t *ps)
Retain a pointer to the decoder.
This increments the reference count on the decoder, allowing it to be shared between multiple parent objects. In general you will not need to use this function, ever. It is mainly here for the convenience of scripting language bindings.pointer to retained decoder.
References ps_decoder_s::refcount.
int ps_free(ps_decoder_t *ps)
Finalize the decoder.
This releases all resources associated with the decoder, including any language models or grammars which have been added to it, and the initial configuration object passed to ps_init(). ps Decoder to be freed. New reference count (0 if freed).
References ps_decoder_s::refcount, dict_free, ps_decoder_s::dict, dict2pid_free, ps_decoder_s::d2p, acmod_free, ps_decoder_s::acmod, ps_decoder_s::lmath, ps_decoder_s::config, ps_decoder_s::uttid.
Referenced by ps_init.
char const* ps_get_uttid(ps_decoder_t *ps)
Get current utterance ID.
ps Decoder to query. Read-only string of the current utterance ID. This is valid only until the beginning of the next utterance.
References ps_decoder_s::uttid.
cmd_ln_t* ps_get_config(ps_decoder_t *ps)
Get the configuration object for this decoder.
The configuration object for this decoder. The decoder retains ownership of this pointer, so you should not attempt to free it manually. Use cmd_ln_retain() if you wish to reuse it elsewhere.
References ps_decoder_s::config.
logmath_t* ps_get_logmath(ps_decoder_t *ps)
Get the log-math computation object for this decoder.
The log-math object for this decoder. The decoder retains ownership of this pointer, so you should not attempt to free it manually. Use logmath_retain() if you wish to reuse it elsewhere.
References ps_decoder_s::lmath.
Referenced by ps_end_utt.
fe_t* ps_get_fe(ps_decoder_t *ps)
Get the feature extraction object for this decoder.
The feature extraction object for this decoder. The decoder retains ownership of this pointer, so you should not attempt to free it manually. Use fe_retain() if you wish to reuse it elsewhere.
References ps_decoder_s::acmod, acmod_s::fe.
feat_t* ps_get_feat(ps_decoder_t *ps)
Get the dynamic feature computation object for this decoder.
The dynamic feature computation object for this decoder. The decoder retains ownership of this pointer, so you should not attempt to free it manually. Use feat_retain() if you wish to reuse it elsewhere.
References ps_decoder_s::acmod, acmod_s::fcb.
ps_mllr_t* ps_update_mllr(ps_decoder_t *ps, ps_mllr_t *mllr)
Adapt current acoustic model using a linear transform.
mllr The new transform to use, or NULL to update the existing transform. The decoder retains ownership of this pointer, so you should not attempt to free it manually. Use ps_mllr_retain() if you wish to reuse it elsewhere. The updated transform object for this decoder, or NULL on failure.
References acmod_update_mllr, ps_decoder_s::acmod.
int ps_set_search(ps_decoder_t *ps, const char *name)
Actives search with the provided name.
Activates search with the provided name. The search must be added before using either ps_set_fsg(), ps_set_lm() or ps_set_kws().0 on success, 1 on failure
References ps_decoder_s::search.
Referenced by ps_reinit.
const char* ps_get_search(ps_decoder_t *ps)
Returns name of curent search in decoder.
ps_set_search
References ps_decoder_s::searches, ps_decoder_s::search.
int ps_unset_search(ps_decoder_t *ps, const char *name)
Unsets the search and releases related resources.
Unsets the search previously added with using either ps_set_fsg(), ps_set_lm() or ps_set_kws().ps_set_fsg ps_set_lm ps_set_kws
References ps_decoder_s::searches, ps_decoder_s::search.
ps_search_iter_t* ps_search_iter(ps_decoder_t *ps)
Returns iterator over current searches.
ps_set_search
References ps_decoder_s::searches.
ps_search_iter_t* ps_search_iter_next(ps_search_iter_t *itor)
Updates search iterator to point to the next position.
This function automatically frees the iterator object upon reaching the final entry. ps_set_search
const char* ps_search_iter_val(ps_search_iter_t *itor)
Retrieves the name of the search the iterator points to.
Updates search iterator to point to the next position.ps_set_search This function automatically frees the iterator object upon reaching the final entry. ps_set_search
void ps_search_iter_free(ps_search_iter_t *itor)
Delete an unfinished search iterator.
ps_set_search
ngram_model_t* ps_get_lm(ps_decoder_t *ps, const char *name)
Get the language model set object for this decoder.
If N-Gram decoding is not enabled, this will return NULL. You will need to enable it using ps_update_lmset().The language model set object for this decoder. The decoder retains ownership of this pointer, so you should not attempt to free it manually. Use ngram_model_retain() if you wish to reuse it elsewhere.
fsg_model_t* ps_get_fsg(ps_decoder_t *ps, const char *name)
Get the finite-state grammar set object for this decoder.
If FSG decoding is not enabled, this returns NULL. Call ps_update_fsgset() to enable it.The current FSG set object for this decoder, or NULL if none is available.
const char* ps_get_kws(ps_decoder_t *ps, const char *name)
Get the current Key phrase to spot.
If KWS is not enabled, this returns NULL. Call ps_update_kws() to enable it.The current keyphrase to spot
static int set_search_internal(ps_decoder_t *ps, const char *name, ps_search_t *search)
int ps_set_lm(ps_decoder_t *ps, const char *name, ngram_model_t *lm)
Adds new search based on N-gram language model.
Associates N-gram search with the provided name. The search can be activated using ps_set_search().ps_set_search.
References ngram_search_init, ps_decoder_s::config, ps_decoder_s::acmod, ps_decoder_s::dict, ps_decoder_s::d2p.
Referenced by ps_reinit, ps_set_lm_file.
int ps_set_lm_file(ps_decoder_t *ps, const char *name, const char *path)
Adds new search based on N-gram language model.
Convenient method to load N-gram model and create a search.ps_set_lm
References ps_decoder_s::config, ps_decoder_s::lmath, ps_set_lm.
Referenced by ps_reinit.
int ps_set_kws(ps_decoder_t *ps, const char *name, const char *keyfile)
Adds keywords from a file to spotting.
Associates KWS search with the provided name. The search can be activated using ps_set_search().ps_set_search
References ps_decoder_s::config, ps_decoder_s::acmod, ps_decoder_s::dict, ps_decoder_s::d2p.
Referenced by ps_reinit.
int ps_set_keyphrase(ps_decoder_t *ps, const char *name, const char *keyphrase)
Adds new keyword to spot.
Associates KWS search with the provided name. The search can be activated using ps_set_search().ps_set_search
References ps_decoder_s::config, ps_decoder_s::acmod, ps_decoder_s::dict, ps_decoder_s::d2p.
Referenced by ps_reinit.
int ps_set_fsg(ps_decoder_t *ps, const char *name, fsg_model_t *fsg)
Adds new search based on finite state grammar.
Associates FSG search with the provided name. The search can be activated using ps_set_search().ps_set_search
References ps_decoder_s::config, ps_decoder_s::acmod, ps_decoder_s::dict, ps_decoder_s::d2p.
Referenced by ps_reinit, ps_set_jsgf_file.
int ps_set_jsgf_file(ps_decoder_t *ps, const char *name, const char *path)
Adds new search using JSGF model.
Convenient method to load JSGF model and create a search.ps_set_fsg
References ps_decoder_s::config, ps_decoder_s::lmath, ps_set_fsg.
Referenced by ps_reinit.
int ps_load_dict(ps_decoder_t *ps, char const *dictfile, char const *fdictfile, char const *format)
Reload the pronunciation dictionary from a file.
This function replaces the current pronunciation dictionary with the one stored in dictfile. This also causes the active search module(s) to be reinitialized, in the same manner as calling ps_add_word() with update=TRUE. dictfile Path to dictionary file to load. fdictfile Path to filler dictionary to load, or NULL to keep the existing filler dictionary. format Format of the dictionary file, or NULL to determine automatically (currently unused,should be NULL)
References ps_args, ps_decoder_s::config, dict_init, ps_decoder_s::acmod, acmod_s::mdef, dict2pid_build, dict_free, ps_decoder_s::dict, dict2pid_free, ps_decoder_s::d2p, ps_decoder_s::searches.
int ps_save_dict(ps_decoder_t *ps, char const *dictfile, char const *format)
Dump the current pronunciation dictionary to a file.
This function dumps the current pronunciation dictionary to a tex dictfile Path to file where dictionary will be written. format Format of the dictionary file, or NULL for the default (text) format (currently unused, should be NULL)
References dict_write, ps_decoder_s::dict.
int ps_add_word(ps_decoder_t *ps, char const *word, char const *phones, int update)
Add a word to the pronunciation dictionary.
This function adds a word to the pronunciation dictionary and the current language model (but, obviously, not to the current FSG if FSG mode is enabled). If the word is already present in one or the other, it does whatever is necessary to ensure that the word can be recognized. word Word string to add. phones Whitespace-separated list of phoneme strings describing pronunciation of word. update If TRUE, update the search module (whichever one is currently active) to recognize the newly added word. If adding multiple words, it is more efficient to pass FALSE here in all but the last word. The internal ID (>= 0) of the newly added word, or <0 on failure.
References bin_mdef_ciphone_id, ps_decoder_s::acmod, acmod_s::mdef, dict_add_word, ps_decoder_s::dict, dict2pid_add_word, ps_decoder_s::d2p, ps_decoder_s::searches, ps_decoder_s::search.
int ps_decode_raw(ps_decoder_t *ps, FILE *rawfh, char const *uttid, long maxsamps)
Decode a raw audio stream.
No headers are recognized in this files. The configuration parameters -samprate and -input_endian are used to determine the sampling rate and endianness of the stream, respectively. Audio is always assumed to be 16-bit signed PCM. ps Decoder. rawfh Previously opened file stream. uttid Utterance ID (or NULL to generate automatically). maxsamps Maximum number of samples to read from rawfh, or -1 to read until end-of-file. Number of samples of audio.
References ps_start_utt, ps_process_raw, ps_end_utt.
int ps_start_utt(ps_decoder_t *ps, char const *uttid)
Start utterance processing.
This function should be called before any utterance data is passed to the decoder. It marks the start of a new utterance and reinitializes internal data structures. ps Decoder to be started. uttid String uniquely identifying this utterance. If NULL, one will be created. 0 for success, <0 on error.
References ps_decoder_s::search, ps_decoder_s::perf, ps_decoder_s::uttid, ps_decoder_s::uttno, ps_lattice_free, ps_search_s::dag, ps_search_s::last_link, ps_search_s::post, ps_search_s::hyp_str, acmod_start_utt, ps_decoder_s::acmod, ps_decoder_s::mfclogdir, acmod_set_mfcfh, ps_decoder_s::rawlogdir, acmod_set_rawfh, ps_decoder_s::senlogdir, acmod_set_senfh, ps_decoder_s::phone_loop.
Referenced by ps_decode_raw, ps_decode_senscr.
static int ps_search_forward(ps_decoder_t *ps)
int ps_decode_senscr(ps_decoder_t *ps, FILE *senfh, char const *uttid)
Decode a senone score dump file.
ps Decoder fh Previously opened file handle positioned at start of file. uttid Utterance ID (or NULL to generate automatically). Number of frames read.
References ps_start_utt, acmod_set_insenfh, ps_decoder_s::acmod, acmod_read_scores, ps_end_utt.
int ps_process_raw(ps_decoder_t *ps, int16 const *data, size_t n_samples, int no_search, int full_utt)
Decode raw audio data.
ps Decoder. no_search If non-zero, perform feature extraction but don't do any recognition yet. This may be necessary if your processor has trouble doing recognition in real-time. full_utt If non-zero, this block of data is a full utterance worth of data. This may allow the recognizer to produce more accurate results. Number of frames of data searched, or <0 for error.
References ps_decoder_s::acmod, acmod_s::state, ACMOD_IDLE, acmod_set_grow, acmod_process_raw.
Referenced by ps_decode_raw.
int ps_process_cep(ps_decoder_t *ps, mfcc_t **data, int32 n_frames, int no_search, int full_utt)
int ps_end_utt(ps_decoder_t *ps)
End utterance processing.
ps Decoder. 0 for success, <0 on error
References acmod_end_utt, ps_decoder_s::acmod, ps_decoder_s::perf, ps_decoder_s::phone_loop, acmod_s::output_frame, ps_decoder_s::pl_window, ps_decoder_s::search, ps_decoder_s::config, ps_get_hyp, ps_seg_iter, ps_seg_next, ps_seg_word, ps_seg_frames, ps_seg_prob, ps_get_logmath.
Referenced by ps_decode_raw, ps_decode_senscr.
char const* ps_get_hyp(ps_decoder_t *ps, int32 *out_best_score, char const **out_uttid)
Get hypothesis string and path score.
ps Decoder. out_best_score Output: path score corresponding to returned string. out_uttid Output: utterance ID for this utterance. String containing best hypothesis at this point in decoding. NULL if no hypothesis is available.
References ps_decoder_s::perf, ps_decoder_s::search, ps_decoder_s::uttid.
Referenced by ps_end_utt.
char const* ps_get_hyp_final(ps_decoder_t *ps, int32 *out_is_final)
Get hypothesis string and final flag.
ps Decoder. out_is_best_score Output: if hypothesis is reached final state in the grammar. String containing best hypothesis at this point in decoding. NULL if no hypothesis is available.
References ps_decoder_s::perf, ps_decoder_s::search.
int32 ps_get_prob(ps_decoder_t *ps, char const **out_uttid)
Get posterior probability.
Unless the -bestpath option is enabled, this function will always return zero (corresponding to a posterior probability of 1.0). Even if -bestpath is enabled, it will also return zero when called on a partial result. Ongoing research into effective confidence annotation for partial hypotheses may result in these restrictions being lifted in future versions. ps Decoder. out_uttid Output: utterance ID for this utterance. Posterior probability of the best hypothesis.
References ps_decoder_s::perf, ps_decoder_s::search, ps_decoder_s::uttid.
ps_seg_t* ps_seg_iter(ps_decoder_t *ps, int32 *out_best_score)
Get an iterator over the word segmentation for the best hypothesis.
ps Decoder. out_best_score Output: path score corresponding to hypothesis. Iterator over the best hypothesis at this point in decoding. NULL if no hypothesis is available.
References ps_decoder_s::perf, ps_decoder_s::search.
Referenced by ps_end_utt.
ps_seg_t* ps_seg_next(ps_seg_t *seg)
Get the next segment in a word segmentation.
seg Segment iterator. Updated iterator with the next segment. NULL at end of utterance (the iterator will be freed in this case).
Referenced by ps_end_utt.
char const* ps_seg_word(ps_seg_t *seg)
Get word string from a segmentation iterator.
seg Segment iterator. Read-only string giving string name of this segment. This is only valid until the next call to ps_seg_next().
References ps_seg_s::word.
Referenced by ps_end_utt.
void ps_seg_frames(ps_seg_t *seg, int *out_sf, int *out_ef)
Get inclusive start and end frames from a segmentation iterator.
These frame numbers are inclusive, i.e. the end frame refers to the last frame in which the given word or other segment was active. Therefore, the actual duration is *out_ef - *out_sf + 1. seg Segment iterator. out_sf Output: First frame index in segment. out_sf Output: Last frame index in segment.
References ps_seg_s::sf, ps_seg_s::ef.
Referenced by ps_end_utt.
int32 ps_seg_prob(ps_seg_t *seg, int32 *out_ascr, int32 *out_lscr, int32 *out_lback)
Get language, acoustic, and posterior probabilities from a segmentation iterator.
Unless the -bestpath option is enabled, this function will always return zero (corresponding to a posterior probability of 1.0). Even if -bestpath is enabled, it will also return zero when called on a partial result. Ongoing research into effective confidence annotation for partial hypotheses may result in these restrictions being lifted in future versions. out_ascr Output: acoustic model score for this segment. out_lscr Output: language model score for this segment. out_lback Output: language model backoff mode for this segment (i.e. the number of words used in calculating lscr). This field is, of course, only meaningful for N-Gram models. Log posterior probability of current segment. Log is expressed in the log-base used in the decoder. To convert to linear floating-point, use logmath_exp(ps_get_logmath(), pprob).
References ps_seg_s::ascr, ps_seg_s::lscr, ps_seg_s::lback, ps_seg_s::prob.
Referenced by ps_end_utt.
void ps_seg_free(ps_seg_t *seg)
Finish iterating over a word segmentation early, freeing resources.
ps_lattice_t* ps_get_lattice(ps_decoder_t *ps)
Get word lattice.
There isn't much you can do with this so far, a public API will appear in the future. ps Decoder. Word lattice object containing all hypotheses so far. NULL if no hypotheses are available. This pointer is owned by the decoder and you should not attempt to free it manually. It is only valid until the next utterance, unless you use ps_lattice_retain() to retain it.
References ps_decoder_s::search.
Referenced by ps_nbest.
ps_nbest_t* ps_nbest(ps_decoder_t *ps, int sf, int ef, char const *ctx1, char const *ctx2)
Get an iterator over the best hypotheses, optionally within a selected region of the utterance.
Iterator is empty now, it must be advanced with ps_nbest_next first. The function may also return a NULL which means that there is no hypothesis available for this utterance. ps Decoder. sf Start frame for N-best search (0 for whole utterance) ef End frame for N-best search (-1 for whole utterance) ctx1 First word of trigram context (NULL for whole utterance) ctx2 First word of trigram context (NULL for whole utterance) Iterator over N-best hypotheses or NULL if no hypothesis is available
References ps_decoder_s::search, ps_get_lattice, dict_wordid, ps_astar_start.
void ps_nbest_free(ps_nbest_t *nbest)
Finish N-best search early, releasing resources.
nbest N-best iterator.
References ps_astar_finish.
Referenced by ps_nbest_next.
ps_nbest_t* ps_nbest_next(ps_nbest_t *nbest)
Move an N-best list iterator forward.
nbest N-best iterator. Updated N-best iterator, or NULL if no more hypotheses are available (iterator is freed ni this case).
References ps_astar_next, ps_nbest_free.
char const* ps_nbest_hyp(ps_nbest_t *nbest, int32 *out_score)
Get the hypothesis string from an N-best list iterator.
nbest N-best iterator. out_score Output: Path score for this hypothesis. String containing next best hypothesis.
References ps_latpath_s::score, ps_astar_hyp.
ps_seg_t* ps_nbest_seg(ps_nbest_t *nbest, int32 *out_score)
Get the word segmentation from an N-best list iterator.
nbest N-best iterator. out_score Output: Path score for this hypothesis. Iterator over the next best hypothesis.
References ps_latpath_s::score, ps_astar_seg_iter.
int ps_get_n_frames(ps_decoder_t *ps)
Get the number of frames of data searched.
Note that there is a delay between this and the number of frames of audio which have been input to the system. This is due to the fact that acoustic features are computed using a sliding window of audio, and dynamic features are computed over a sliding window of acoustic features. ps Decoder. Number of frames of speech data which have been recognized so far.
References ps_decoder_s::acmod, acmod_s::output_frame.
void ps_get_utt_time(ps_decoder_t *ps, double *out_nspeech, double *out_ncpu, double *out_nwall)
Get performance information for the current utterance.
ps Decoder. out_nspeech Output: Number of seconds of speech. out_ncpu Output: Number of seconds of CPU time used. out_nwall Output: Number of seconds of wall time used.
References ps_decoder_s::config, ps_decoder_s::acmod, acmod_s::output_frame, ps_decoder_s::perf.
void ps_get_all_time(ps_decoder_t *ps, double *out_nspeech, double *out_ncpu, double *out_nwall)
Get overall performance information.
ps Decoder. out_nspeech Output: Number of seconds of speech. out_ncpu Output: Number of seconds of CPU time used. out_nwall Output: Number of seconds of wall time used.
References ps_decoder_s::config, ps_decoder_s::n_frame, ps_decoder_s::perf.
uint8 ps_get_vad_state(ps_decoder_t *ps)
Checks if the last feed audio buffer contained speech.
ps Decoder. 1 if last buffer contained speech, 0 - otherwise
References ps_decoder_s::acmod, acmod_s::fe.
void ps_search_init(ps_search_t *search, ps_searchfuncs_t *vt, cmd_ln_t *config, acmod_t *acmod, dict_t *dict, dict2pid_t *d2p)
Initialize base structure.
References ps_search_s::vt, ps_search_s::config, ps_search_s::acmod, ps_search_s::d2p, dict2pid_retain, ps_search_s::dict, dict_retain, ps_search_s::start_wid, ps_search_s::finish_wid, ps_search_s::silence_wid, ps_search_s::n_words, dict_size.
Referenced by ngram_search_init.
void ps_search_base_reinit(ps_search_t *search, dict_t *dict, dict2pid_t *d2p)
Re-initialize base structure with new dictionary.
References dict_free, ps_search_s::dict, dict2pid_free, ps_search_s::d2p, dict_retain, ps_search_s::start_wid, ps_search_s::finish_wid, ps_search_s::silence_wid, ps_search_s::n_words, dict_size, dict2pid_retain.
void ps_search_deinit(ps_search_t *search)
De-initialize base structure.
References dict_free, ps_search_s::dict, dict2pid_free, ps_search_s::d2p, ps_search_s::hyp_str, ps_lattice_free, ps_search_s::dag.
Referenced by ngram_search_free.