ps_lattice_internal.h
typedef struct latlink_list_s latlink_list_t
Linked list of DAG link pointers.
Because the same link structure is used for forward and reverse links, as well as for the agenda used in bestpath search, we can't store the list pointer inside latlink_t. We could use glist_t here, but it wastes 4 bytes per entry on 32-bit machines.
typedef struct dag_seg_s dag_seg_t
Segmentation "iterator" for backpointer table results.
typedef struct ps_latpath_s ps_latpath_t
Partial path structure used in N-best (A*) search.
Each partial path (latpath_t) is constructed by extending another partial pathparentby one node.
typedef struct ps_astar_s ps_astar_t
A* search structure.
typedef struct astar_seg_s astar_seg_t
Segmentation "iterator" for A* search results.
ps_lattice_t* ps_lattice_init_search(ps_search_t *search, int n_frame)
Construct an empty word graph with reference to a search structure.
References ps_lattice_s::search, ps_lattice_s::dict, dict_retain, ps_search_s::dict, ps_lattice_s::lmath, ps_search_s::acmod, acmod_s::lmath, ps_lattice_s::frate, ps_search_s::config, ps_lattice_s::silence, ps_lattice_s::n_frames, ps_lattice_s::latnode_alloc, ps_lattice_s::latlink_alloc, ps_lattice_s::latlink_list_alloc, ps_lattice_s::refcount.
Referenced by ngram_search_lattice.
void ps_lattice_bypass_fillers(ps_lattice_t *dag, int32 silpen, int32 fillpen)
Bypass filler words.
References ps_lattice_s::nodes, ps_latnode_s::next, ps_lattice_s::end, dict_filler_word, ps_lattice_s::dict, ps_latnode_s::basewid, ps_latnode_s::entries, ps_lattice_s::silence, ps_latlink_s::ascr, ps_latnode_s::exits, ps_latlink_s::to, ps_latlink_s::from, ps_lattice_link, ps_latlink_s::ef, ps_latnode_s::reachable.
Referenced by ngram_search_lattice, ps_lattice_read.
void ps_lattice_delete_unreachable(ps_lattice_t *dag)
Remove nodes marked as unreachable.
References ps_lattice_s::nodes, ps_latnode_s::next, ps_latnode_s::reachable, ps_latnode_s::id.
Referenced by ngram_search_lattice, ps_lattice_read, ps_lattice_posterior_prune.
void ps_lattice_pushq(ps_lattice_t *dag, ps_latlink_t *link)
Add an edge to the traversal queue.
References ps_lattice_s::q_head, ps_lattice_s::q_tail, latlink_list_new.
Referenced by ps_lattice_traverse_edges, ps_lattice_traverse_next, ps_lattice_reverse_edges, ps_lattice_reverse_next.
ps_latlink_t* ps_lattice_popq(ps_lattice_t *dag)
Remove an edge from the traversal queue.
References ps_lattice_s::q_head, ps_lattice_s::latlink_list_alloc, ps_lattice_s::q_tail.
Referenced by ps_lattice_delq, ps_lattice_traverse_next, ps_lattice_reverse_next.
void ps_lattice_delq(ps_lattice_t *dag)
Clear and reset the traversal queue.
References ps_lattice_popq.
Referenced by ps_lattice_traverse_edges, ps_lattice_traverse_next, ps_lattice_reverse_edges, ps_lattice_reverse_next.
latlink_list_t* latlink_list_new(ps_lattice_t *dag, ps_latlink_t *link, latlink_list_t *next)
Create a new lattice link element.
References ps_lattice_s::latlink_list_alloc.
Referenced by ps_lattice_pushq.
char const* ps_lattice_hyp(ps_lattice_t *dag, ps_latlink_t *link)
Get hypothesis string after bestpath search.
References dict_real_word, ps_lattice_s::dict, ps_latlink_s::to, ps_latnode_s::basewid, ps_latlink_s::from, ps_lattice_s::hyp_str.
ps_seg_t* ps_lattice_seg_iter(ps_lattice_t *dag, ps_latlink_t *link, float32 lwf)
Get hypothesis segmentation iterator after bestpath search.
References dag_seg_s::base, ps_seg_s::vt, ps_seg_s::search, ps_lattice_s::search, ps_seg_s::lwf, dag_seg_s::n_links, dag_seg_s::norm, ps_lattice_s::norm, dag_seg_s::links.
ps_astar_t* ps_astar_start(ps_lattice_t *dag, ngram_model_t *lmset, float32 lwf, int sf, int ef, int w1, int w2)
Begin N-Gram based A* search on a word graph.
sf Starting frame for N-best search. ef Ending frame for N-best search, or -1 for last frame. w1 First context word, or -1 for none. w2 Second context word, or -1 for none. 0 for success, <0 on error.
References ps_latnode_s::basewid, ps_lattice_s::end, ps_latnode_s::exits, ps_astar_s::latpath_alloc, ps_lattice_s::n_frames, ps_latnode_s::next, ps_latpath_s::node, ps_lattice_s::nodes, ps_latpath_s::parent, ps_latnode_s::rem_score, ps_latpath_s::score, SENSCR_SHIFT, ps_latnode_s::sf, WORST_SCORE.
Referenced by ps_nbest.
ps_latpath_t* ps_astar_next(ps_astar_t *nbest)
Find next best hypothesis of A* on a word graph.
a complete path, or NULL if no more hypotheses exist.
References ps_lattice_s::end, ps_latnode_s::fef, ps_latpath_s::next, ps_latpath_s::node, ps_latnode_s::sf.
Referenced by ps_nbest_next.
void ps_astar_finish(ps_astar_t *nbest)
Finish N-best search, releasing resources associated with it.
References ps_astar_s::hyps, ps_astar_s::latpath_alloc.
Referenced by ps_nbest_free.
char const* ps_astar_hyp(ps_astar_t *nbest, ps_latpath_t *path)
Get hypothesis string from A* search.
References ps_lattice_s::search, ps_latpath_s::parent, dict_real_word, ps_latpath_s::node, ps_latnode_s::basewid, ps_astar_s::hyps.
Referenced by ps_nbest_hyp.
ps_seg_t* ps_astar_seg_iter(ps_astar_t *astar, ps_latpath_t *path, float32 lwf)
Get hypothesis segmentation from A* search.
References ps_seg_s::vt, ps_seg_s::search, ps_lattice_s::search, ps_seg_s::lwf, ps_latpath_s::parent, ps_latpath_s::node.
Referenced by ps_nbest_seg.