ps_mllr.h
typedef struct ps_mllr_s ps_mllr_t
Feature space linear transform object.
POCKETSPHINX_EXPORT ps_mllr_t* ps_mllr_read(char const *file)
Read a speaker-adaptive linear transform from a file.
References ps_mllr_s::refcnt, ps_mllr_s::n_class, ps_mllr_s::n_feat, ps_mllr_s::veclen, ps_mllr_s::A, ps_mllr_s::b, ps_mllr_s::h, ps_mllr_free.
POCKETSPHINX_EXPORT ps_mllr_t* ps_mllr_retain(ps_mllr_t *mllr)
Retain a pointer to a linear transform.
References ps_mllr_s::refcnt.
POCKETSPHINX_EXPORT int ps_mllr_free(ps_mllr_t *mllr)
Release a pointer to a linear transform.
References ps_mllr_s::refcnt, ps_mllr_s::n_feat, ps_mllr_s::A, ps_mllr_s::b, ps_mllr_s::h, ps_mllr_s::veclen.
Referenced by acmod_free, acmod_update_mllr, ps_mllr_read.