ps_alignment.c
VECTOR_GROW
ps_alignment_t* ps_alignment_init(dict2pid_t *d2p)
Create a new, empty alignment.
References dict2pid_retain.
int ps_alignment_free(ps_alignment_t *al)
Release an alignment.
References dict2pid_free.
static void* vector_grow_one(void *ptr, uint16 *n_alloc, uint16 *n, size_t item_size)
static ps_alignment_entry_t* ps_alignment_vector_grow_one(ps_alignment_vector_t *vec)
static void ps_alignment_vector_empty(ps_alignment_vector_t *vec)
int ps_alignment_add_word(ps_alignment_t *al, int32 wid, int duration)
Append a word.
int ps_alignment_populate(ps_alignment_t *al)
Populate lower layers using available word information.
References dict2pid_t::dict, dict2pid_t::mdef, BAD_SSID, dict_pron, dict2pid_internal, dict2pid_rssid, xwdssid_t::ssid, xwdssid_t::cimap, BAD_SENID.
int ps_alignment_populate_ci(ps_alignment_t *al)
Populate lower layers using context-independent phones.
References dict2pid_t::dict, dict2pid_t::mdef, dict_pron, BAD_SSID, BAD_SENID.
int ps_alignment_propagate(ps_alignment_t *al)
Propagate timing information up from state sequence.
int ps_alignment_n_words(ps_alignment_t *al)
Number of words.
int ps_alignment_n_phones(ps_alignment_t *al)
Number of phones.
int ps_alignment_n_states(ps_alignment_t *al)
Number of states.
ps_alignment_iter_t* ps_alignment_words(ps_alignment_t *al)
Iterate over the alignment starting at the first word.
ps_alignment_iter_t* ps_alignment_phones(ps_alignment_t *al)
Iterate over the alignment starting at the first phone.
ps_alignment_iter_t* ps_alignment_states(ps_alignment_t *al)
Iterate over the alignment starting at the first state.
ps_alignment_entry_t* ps_alignment_iter_get(ps_alignment_iter_t *itor)
Get the alignment entry pointed to by an iterator.
int ps_alignment_iter_free(ps_alignment_iter_t *itor)
Release an iterator before completing all iterations.
Referenced by ps_alignment_iter_goto, ps_alignment_iter_next, ps_alignment_iter_prev.
ps_alignment_iter_t* ps_alignment_iter_goto(ps_alignment_iter_t *itor, int pos)
Move alignment iterator to given index.
References ps_alignment_iter_free.
ps_alignment_iter_t* ps_alignment_iter_next(ps_alignment_iter_t *itor)
Move an alignment iterator forward.
References ps_alignment_iter_free.
ps_alignment_iter_t* ps_alignment_iter_prev(ps_alignment_iter_t *itor)
Move an alignment iterator back.
References ps_alignment_iter_free.
ps_alignment_iter_t* ps_alignment_iter_up(ps_alignment_iter_t *itor)
Get a new iterator starting at the parent of the current node.
ps_alignment_iter_t* ps_alignment_iter_down(ps_alignment_iter_t *itor)
Get a new iterator starting at the first child of the current node.