
SUCCESS_OK = 0

ERROR_GENERIC     = 1
ERROR_INTERNET    = 2
ERROR_TIMEOUT     = 3
ERROR_CRITICAL    = 4
ERROR_MAX_RETRIES = 5

WARN_GENERIC      = 1
WARN_ABORTED      = 2
WARN_INTERNET     = 3
WARN_TIMEOUT      = 4
