#!/bin/bash

LUCIDA_ROOT=`pwd`
LUCIDA_ROOT="${LUCIDA_ROOT%/questionanswering/googleassist}"

if [ -f 'configuration.py' ]; then
  if [ -f '.config' ]; then
    source ./.config
  fi
  set -e
  source ./configuration.py
  set +e
  echo "# ----- LAST STABLE CONFIGURATION ----- #" > .config
  echo "#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN" >> .config
  echo "CREDENTIALS_DIR=\"$CREDENTIALS_DIR\"" >> .config
  echo "GA_CLIENT_SECRET=\"$GA_CLIENT_SECRET\"" >> .config
  echo "TTS_ENGINE=\"$TTS_ENGINE\"" >> .config
  echo "STT_ENGINE=\"$STT_ENGINE\"" >> .config
else
  echo "You'll need to answer a few questions for first time setup. To change any of these options see configuration.py. To reset delete configuration.py"
  rm -f .config
fi


echo "#" > configuration.py
echo "# Configuration file for Google Assistant Speech to Text microservice" >> configuration.py
echo "#" >> configuration.py
echo "" >> configuration.py
echo "# NOTE: If you manually update the file keep in mind that this is both a python and bash file. Take care of the syntax accordingly" >> configuration.py

while [ -z "$CREDENTIALS_DIR" ] || [ -z "$GA_CLIENT_SECRET" ]; do
  echo ""
  secrets=($(find "`pwd`" -type f -name "*.json" | while read file; do grep "$file" -e "project_id" 2>&1 1>/dev/null; if [ $? -eq 0 ]; then echo "$file"; fi; done))
  if [ -d "$LUCIDA_ROOT/speechrecognition/decoders/googleassist" ]; then
    secrets=(${secrets[@]} $(find "$LUCIDA_ROOT/speechrecognition/decoders/googleassist" -type f -name "*.json" | while read file; do grep "$file" -e "project_id" 2>&1 1>/dev/null; if [ $? -eq 0 ]; then echo "$file"; fi; done))
    if [ -f "$LUCIDA_ROOT/speechrecognition/decoders/googleassist/configuration.py" ]; then
      set -e
      source "$LUCIDA_ROOT/speechrecognition/decoders/googleassist/configuration.py"
      set +e
      if [ ! -z "$CREDENTIALS_DIR" ] && [ -d "$CREDENTIALS_DIR" ] && [ ! -z "$GA_CLIENT_SECRET" ] && [ -f "$GA_CLIENT_SECRET" ]; then
        echo "Successfully loaded credentials directory and Google client secret from Google Asssitant question answering microservice"
        break
      fi
    fi
  fi

  GA_CLIENT_SECRET=
  CREDENTIALS_DIR=
  mkdir -p auth
  CREDENTIALS_DIR=`pwd`"/auth"
  if [ ! -z "$secrets" ]; then
    echo "The following possible credentials were found in the Google Assitant directory. Select which one you want to use. You can also hit 0 to type in a custom path. (0-"${#secrets[*]}")"
    echo ""
    count=1
    for secret in ${secrets[@]}; do echo "[$count] $secret"; count=$(($count+1)); done
    echo "[0] Enter a custom path"
    while [ -z "$GA_CLIENT_SECRET" ]; do
      echo ""
      printf "Enter your choice [1]: "
      read response
      if [ -z "$response" ]; then response=1; fi
      if ! [[ "$response" =~ ^[0-9]+$ ]] ; then
        echo "Choice should be a number!! Try again..."
        continue
      fi
      if [ "$response" -eq 0 ]; then
        printf "Enter path to JSON file containing credentials: "
        read response
        response=`echo "$response" | sed s#^~/#$HOME/#`
        if [ -f "$response" ]; then
          grep "$response" -e "project_id" 2>&1 1>/dev/null
          if [ $? -eq 0 ]; then
            GA_CLIENT_SECRET=`pwd`"/auth/"$(basename "$response")
            echo ""
            if [[ $response != $GA_CLIENT_SECRET ]]; then
              cp -f "$response" auth 2>&1 1>/dev/null
            fi
          else
            echo "Not a valid client secret: $response"
          fi
        else
          echo "No such file: $response"
        fi
      elif [ $(($response-1)) -lt ${#secrets[*]} ]; then
        response=${secrets[$(($response-1))]}
        if [ -f "$response" ]; then
          GA_CLIENT_SECRET=`pwd`"/auth/"$(basename "$response")
          echo ""
          if [[ $response != $GA_CLIENT_SECRET ]]; then
            cp -f "$response" auth 2>&1 1>/dev/null
          fi
        else
          echo "File $response no longer exists!!! Please try a different choice.."
        fi
      else
        echo "Invalid choice!!! Please try again.."
      fi
    done
  else
    echo "No possible credential was found in the Google Assitant speech decoder directory. If you have one provide its path otherwise create one as explained in README"
    while [ -z "$GA_CLIENT_SECRET" ]; do
      printf "Enter path to JSON file containing credentials: "
      read response
      response=`echo "$response" | sed s#^~/#$HOME/#`
      if [ -f "$response" ]; then
        grep "$response" -e "project_id" 2>&1 1>/dev/null
        if [ $? -eq 0 ]; then
          GA_CLIENT_SECRET=`pwd`"/auth/"$(basename "$response")
          echo ""
          if [[ $response != $GA_CLIENT_SECRET ]]; then
            cp -f "$response" auth 2>&1 1>/dev/null
          fi
        else
          echo "Not a valid client secret: $response"
        fi
      else
        echo "No such file: $response"
      fi
    done
  fi
done

echo "" >> configuration.py
echo "# Lucida root directory. This is the directory which contains commandcenter. This will be shared between QA and STT microservices" >> configuration.py
echo "LUCIDA_ROOT=\"$LUCIDA_ROOT\"" >> configuration.py
echo "" >> configuration.py
echo "# Directory used to store Google Assistant credentials for the client and users. This will be shared between QA and STT microservices" >> configuration.py
echo "CREDENTIALS_DIR=\"$CREDENTIALS_DIR\"" >> configuration.py
echo "" >> configuration.py
echo "# Path to JSON file containing Google client credentials. This will be shared between QA and STT microservices" >> configuration.py
echo "GA_CLIENT_SECRET=\"$GA_CLIENT_SECRET\"" >> configuration.py

while [ -z "$TTS_ENGINE" ]; do
  echo ""
  tts_engine=($(find "$LUCIDA_ROOT/tts/encoders" -mindepth 2 -maxdepth 2 -type f -name "encoder.py" | while read line; do echo "$line" | grep -Poe "(?<=/)[^/]+(?=/encoder.py$)";done))
  echo "Which text to speech engine do you want Google Assistant to use? ( ${tts_engine[@]} )"
  printf "TTS_ENGINE: "
  read response
  if [ -f "$LUCIDA_ROOT/tts/encoders/$response/encoder.py" ]; then
    TTS_ENGINE=$response
    echo ""
  else
    echo "Invalid response!!! Please try again..."
  fi
done

echo "" >> configuration.py
echo "# Which text to speech engine do you want Google Assistant to use? ( ${tts_engine[@]} )" >> configuration.py
echo "TTS_ENGINE=\"$TTS_ENGINE\"" >> configuration.py

while [ -z "$STT_ENGINE" ]; do
  echo ""
  stt_engine=($(find "$LUCIDA_ROOT/speechrecognition/decoders" -mindepth 2 -maxdepth 2 -type f -name "decoder" | while read line; do echo "$line" | grep -Poe "(?<=/)[^/]+(?=/decoder$)";done))
  echo "Which speech to text engine do you want Google Assistant to use? ( ${stt_engine[@]} )"
  printf "STT_ENGINE: "
  read response
  if [ -f "$LUCIDA_ROOT/speechrecognition/decoders/$response/decoder" ]; then
    STT_ENGINE=$response
    echo ""
  else
    echo "Invalid response!!! Please try again..."
  fi
done

echo "" >> configuration.py
echo "# Which speech to text engine do you want Google Assistant to use? ( ${stt_engine[@]} )" >> configuration.py
echo "STT_ENGINE=\"$STT_ENGINE\"" >> configuration.py

rm -f .config
