#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
cd -P "$( dirname "$SOURCE" )"
mkdir -p auth
source env/bin/activate

if [ -f 'config.sh' ]; then
  if [ -f 'config.tmp' ]; then
    . ./config.tmp
  fi
  set -e
  . ./config.sh
  set +e
  echo "# ----- LAST STABLE CONFIGURATION ----- #" > config.tmp
  echo "#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN" >> config.tmp
  echo "GA_CLIENT_SECRET=\"$GA_CLIENT_SECRET\"" >> config.tmp
else
  echo "You'll need to answer a few questions for first time setup. To change any of these options see config.sh. To reset delete config.sh"
  rm -f config.tmp
fi

echo "#" > config.sh
echo "# Configuration file for Google Assistant Microservice" >> config.sh
echo "#" >> config.sh

while [ -z "$GA_CLIENT_SECRET" ]; do
  echo ""
  secrets=($(find . -type f -name "*.json" | while read file; do grep $file -e "project_id" 2>&1 1>/dev/null; if [ $? -eq 0 ]; then echo $file; fi; done))
  if [ $? -eq 0 ]; then
    echo "The following possible credentials were found in the Google Assitant directory. Select which one you want to use. You can also hit 0 to type in a custom path. (0-"${#secrets[*]}")"
    echo ""
    count=1
    for secret in ${secrets[@]}; do echo "[$count] $secret"; count=$(($count+1)); done
    echo "[0] Enter a custom path"
    echo ""
    printf "Enter your choice [1]: "
    read response
    if [ -z "$response" ]; then response=1; fi
    if [ $response -eq 0 ]; then
      while [ -z "$GA_CLIENT_SECRET" ]; do
        printf "Enter path to JSON file containing credentials: "
        read response
        response=`echo $response | sed s#^~/#$HOME/#`
        if [ -f $response ]; then
          GA_CLIENT_SECRET="$response"
        else
          echo "No such file: $response"
        fi
      done
    elif [ $(($response-1)) -lt ${#secrets[*]} ]; then
      response=${secrets[$(($response-1))]}
      if [ -f $response ]; then
        GA_CLIENT_SECRET="$response"
      else
        echo "File $response no longer exists!!! Please try a different choice.."
      fi
    else
      echo "Invalid choice!!! Please try again.."
    fi
  else
    echo "No possible credential was found in the Google Assitant directory. If you have one provide its path otherwise create one as explained in README"
    while [ -z "$GA_CLIENT_SECRET" ]; do
      echo $HOME
      printf "Enter path to JSON file containing credentials: "
      read response
      response=`echo $response | sed s#^~/#$HOME/#`
      if [ -f $response ]; then
        GA_CLIENT_SECRET="$response"
      else
        echo "No such file: $response"
      fi
    done
  fi
done
echo "Using $GA_CLIENT_SECRET as client secret.."
echo "" >> config.sh
echo "# Path to JSON file containing Google credentials. See README" >> config.sh
echo "GA_CLIENT_SECRET=\"$GA_CLIENT_SECRET\"" >> config.sh

rm -f config.tmp
