#!gmake

default:	build

TOPDIR		= ../..

include $(TOPDIR)/Makefile.cfg

# -----------------------------------------------------------------------------

SUBDIRS	      = $(TOOLS)

# -----------------------------------------------------------------------------
# targets
# -----------------------------------------------------------------------------

build: 		subdirs_build

install:	subdirs_install

include $(TOPDIR)/Rules.make

.PHONY: $(SUBDIRS)
# DO NOT DELETE
