agc.c
const char* agc_type_str[][]
String representations of agc_type_t values.
Referenced by agc_type_from_str, feat_init.
const int n_agc_type_str
agc_type_t agc_type_from_str(const char *str)
Convert string representation (from command-line) to agc_type_t.
References agc_type_str, E_FATAL.
agc_t* agc_init(void)
Initialize AGC structure with default values.
References ckd_calloc, agc_s::noise_thresh.
Referenced by feat_init.
void agc_free(agc_t *agc)
Free AGC structure.
References ckd_free.
Referenced by feat_free.
void agc_max(agc_t *agc, mfcc_t **mfc, int32 n_frame)
In: AGC structure (not used)
Apply AGC to the given mfc vectors (normalize all C0 mfc coefficients in the given input such that the max C0 value is 0, by subtracting the input max C0 from all).
References agc_s::obs_max, agc_s::obs_frame, E_INFO.
void agc_emax_set(agc_t *agc, float32 m)
Set the current AGC maximum estimate.
References agc_s::max, E_INFO.
Referenced by feat_init.
float32 agc_emax_get(agc_t *agc)
Get the current AGC maximum estimate.
References agc_s::max.
void agc_emax(agc_t *agc, mfcc_t **mfc, int32 n_frame)
In: AGC structure
Unlike agc_max() this does not require the entire utterance to be available. Call agc_emax_update() at the end of each utterance to update the AGC parameters.
References agc_s::obs_max, agc_s::obs_frame, agc_s::max.
void agc_emax_update(agc_t *agc)
In: AGC structure
References agc_s::obs_frame, agc_s::obs_max, agc_s::obs_utt, agc_s::max, E_INFO.
void agc_noise(agc_t *agc, mfcc_t **cep, int32 nfr)
In: AGC structure
References agc_s::noise_thresh, E_INFO.
void agc_set_threshold(agc_t *agc, float32 threshold)
Set the current AGC noise threshold.
References agc_s::noise_thresh.
float32 agc_get_threshold(agc_t *agc)
Get the current AGC noise threshold.
References agc_s::noise_thresh.