bio.c
BIO_HDRARG_MAX
END_COMMENT
static void bcomment_read(FILE *fp)
static int32 swap_check(FILE *fp)
void bio_hdrarg_free(char **argname, char **argval)
In: Array previously returned by bio_readhdr
References ckd_free.
Referenced by feat_read_lda, bio_readhdr, logmath_read.
int32 bio_writehdr_version(FILE *fp, char *version)
Output: File to write
Also write the byte order magic word. 0 if successful, -1 otherwise.
int32 bio_writehdr(FILE *fp,...)
Write a simple binary file header with only byte order magic word.
0 if successful, -1 otherwise.
References E_ERROR.
int32 bio_readhdr(FILE *fp, char ***argname, char ***argval, int32 *swap)
In: File to read
s3 <argument-name> <argument-value> <argument-name> <argument-value> ... endhdr 4-byte byte-order word used to find file byte ordering relative to host machine. Lines beginning with # are ignored. Memory for name and val allocated by this function; use bio_hdrarg_free to free them. 0 if successful, -1 otherwise.
References ckd_calloc, E_ERROR, ckd_salloc, bio_hdrarg_free.
Referenced by feat_read_lda, logmath_read.
static uint32 chksum_accum(const void *buf, int32 el_sz, int32 n_el, uint32 sum)
static void swap_buf(void *buf, int32 el_sz, int32 n_el)
int32 bio_fread(void *buf, int32 el_sz, int32 n_el, FILE *fp, int32 swap, uint32 *chksum)
In: buffer to write
unlike fread, returns -1 if required number of elements (n_el) not read; also, no byteswapping or checksum accumulation is performed in that case.
Referenced by bio_fread_1d, bio_fread_2d, bio_fread_3d, logmath_read.
int32 bio_fwrite(const void *buf, int32 el_sz, int32 n_el, FILE *fp, int32 swap, uint32 *chksum)
In: buffer to write
the number of elemens written (like fwrite).
References ckd_calloc, ckd_free.
Referenced by bio_fwrite_3d, bio_fwrite_1d, logmath_write.
int32 bio_fread_1d(void **buf, size_t el_sz, uint32 *n_el, FILE *fp, int32 sw, uint32 *ck)
Out: contains array data; allocated by this function; can be freed using ckd_free
4-byte array size (returned in n_el)memory allocated for the array and read (returned in buf) Byteswapping and checksum accumulation performed as necessary. Fails fatally if expected data not read. number of array elements allocated and read; -1 if error.
References bio_fread, E_FATAL, ckd_calloc.
Referenced by bio_fread_2d, bio_fread_3d.
int32 bio_fread_2d(void ***arr, size_t e_sz, uint32 *d1, uint32 *d2, FILE *fp, uint32 swap, uint32 *chksum)
Read a 2-d matrix:
4-byte # rows, # columns (returned in d1, d2, d3)memory allocated for the array and read (returned in buf) Byteswapping and checksum accumulation performed as necessary. Fails fatally if expected data not read. number of array elements allocated and read; -1 if error.
References bio_fread, E_ERROR_SYSTEM, bio_fread_1d, ckd_alloc_2d_ptr.
int32 bio_fread_3d(void ****arr, size_t e_sz, uint32 *d1, uint32 *d2, uint32 *d3, FILE *fp, uint32 swap, uint32 *chksum)
Read a 3-d array (set of matrices)
4-byte # matrices, # rows, # columns (returned in d1, d2, d3)memory allocated for the array and read (returned in buf) Byteswapping and checksum accumulation performed as necessary. Fails fatally if expected data not read. number of array elements allocated and read; -1 if error.
References bio_fread, E_ERROR_SYSTEM, bio_fread_1d, ckd_alloc_3d_ptr.
Referenced by feat_read_lda.
void bio_verify_chksum(FILE *fp, int32 byteswap, uint32 chksum)
In: File to read
Fails fatally if there is a mismatch.
References E_FATAL.
Referenced by logmath_read.
int bio_fwrite_3d(void ***arr, size_t e_sz, uint32 d1, uint32 d2, uint32 d3, FILE *fp, uint32 *chksum)
In: Data to write
Checksum accumulation performed as necessary.number of array elements successfully written or -1 if error.
References bio_fwrite, E_ERROR_SYSTEM, bio_fwrite_1d.
int bio_fwrite_1d(void *arr, size_t e_sz, uint32 d1, FILE *fp, uint32 *chksum)
In: Data to write
Checksum accumulation performed as necessary.number of array elements successfully written or -1 if error.
References bio_fwrite, E_ERROR_SYSTEM.
Referenced by bio_fwrite_3d.
int16* bio_read_wavfile(char const *directory, char const *filename, char const *extension, int32 header, int32 endian, int32 *nsamps)
In: the folder where the file is located
pointer to the data.
References ckd_calloc, E_FATAL_SYSTEM, E_ERROR_SYSTEM, ckd_free.