case.c
void lcase(register char *cp)
void ucase(register char *cp)
int32 strcmp_nocase(const char *str1, const char *str2)
(FIXME! The implementation is incorrect!) Case insensitive string compare.
Return the usual -1, 0, +1, depending on str1 <, =, > str2 (case insensitive, of course). str1 is the first string. str2 is the second string.
References UPPER_CASE.
Referenced by ngram_file_name_to_type, ngram_str_to_type.
int32 strncmp_nocase(const char *str1, const char *str2, size_t len)
Like strcmp_nocase() but with a maximum length.
References UPPER_CASE.
Referenced by ngram_file_name_to_type.