ckd_alloc.h
ckd_calloc
Macros to simplify the use of above functions.
One should use these, rather than target functions directly. Macro for ckd_calloc
Referenced by __ckd_calloc_4d__, agc_init, bio_fread_1d, bio_fwrite, bio_read_wavfile, bio_readhdr, bit_encode_attach, cmd_ln_init, cmd_ln_parse_file_r, cmd_ln_parse_r, feat_array_alloc, feat_init, feat_lda_transform, feat_s2mfc2feat, feat_set_subvecs, fopen_compchk, glist_add_float32, glist_add_float64, glist_add_int32, glist_add_ptr, glist_add_uint32, glist_insert_float32, glist_insert_float64, glist_insert_int32, glist_insert_ptr, glist_insert_uint32, hash_table_iter, hash_table_new, heap_new, huff_code_build_int, huff_code_build_str, huff_code_read, jsgf_grammar_new, lineiter_start, listelem_alloc_init, logmath_init, logmath_read, mmio_file_read, ngram_iter, ngram_model_add_class, ngram_model_set_init, ngram_model_set_iter, ngram_model_set_map_words, ngram_model_set_read, ngram_prob, ngram_probv, ngram_score, parse_subvecs, pctr_new, sbevent_init, sbmsgq_init, sbmtx_init, sbthread_start, string_join, yin_init.
ckd_malloc
Macro for ckd_malloc
Referenced by lineiter_start, fread_line.
ckd_realloc
Macro for ckd_realloc
Referenced by feat_s2mfc2feat, ngram_model_add_class, ngram_model_set_add, bitvec_realloc, cmd_ln_parse_file_r, fread_line.
ckd_salloc
Macro for ckd_salloc
Referenced by feat_init, jsgf_grammar_new, ngram_model_casefold, ngram_model_set_init, ngram_model_set_read, ngram_model_set_add, ngram_model_set_map_words, bio_readhdr, cmd_ln_init, cmd_ln_parse_file_r, cmd_ln_set_str_r, pctr_new.
ckd_calloc_2d
Macro for ckd_calloc_2d
Referenced by yin_init, feat_array_alloc, feat_init, ngram_model_set_add, ngram_model_set_map_words.
ckd_calloc_3d
Macro for ckd_calloc_3d
ckd_calloc_4d
Macro for ckd_calloc_4d
ckd_alloc_2d_ptr
Macro for ckd_alloc_2d_ptr
Referenced by bio_fread_2d.
ckd_free_2d_ptr
Free only the pointer arrays allocated with ckd_alloc_2d_ptr().
ckd_alloc_3d_ptr
Macro for ckd_alloc_3d_ptr
Referenced by bio_fread_3d.
ckd_free_3d_ptr
Free only the pointer arrays allocated with ckd_alloc_3d_ptr().
jmp_buf* ckd_set_jump(jmp_buf *env, int abort)
Control behaviour of the program when allocation fails.
Although your program is probably toast when memory allocation fails, it is also probably a good idea to be able to catch these errors and alert the user in some way. Either that, or you might want the program to call abort() so that you can debug the failed code. This function allows you to control that behaviour. env Pointer to a jmp_buf initialized with setjmp(), or NULL to remove a previously set jump target. abort If non-zero, the program will call abort() when allocation fails rather than exiting or calling longjmp(). Pointer to a previously set jmp_buf, if any.
void ckd_fail(char *format,...)
Fail (with a message) according to behaviour specified by ckd_set_jump().
SPHINXBASE_EXPORT void* __ckd_calloc__(size_t n_elem, size_t elem_size, const char *caller_file, int caller_line)
SPHINXBASE_EXPORT void* __ckd_malloc__(size_t size, const char *caller_file, int caller_line)
SPHINXBASE_EXPORT void* __ckd_realloc__(void *ptr, size_t new_size, const char *caller_file, int caller_line)
SPHINXBASE_EXPORT char* __ckd_salloc__(const char *origstr, const char *caller_file, int caller_line)
Like strdup, except that if an error occurs it prints a diagnostic message and exits.
If origin in NULL the function also returns NULL.
SPHINXBASE_EXPORT void* __ckd_calloc_2d__(size_t d1, size_t d2, size_t elemsize, const char *caller_file, int caller_line)
Allocate a 2-D array and return ptr to it (ie, ptr to vector of ptrs).
The data area is allocated in one block so it can also be treated as a 1-D array.
SPHINXBASE_EXPORT void* __ckd_calloc_3d__(size_t d1, size_t d2, size_t d3, size_t elemsize, const char *caller_file, int caller_line)
Allocate a 3-D array and return ptr to it.
The data area is allocated in one block so it can also be treated as a 1-D array.
SPHINXBASE_EXPORT void**** __ckd_calloc_4d__(size_t d1, size_t d2, size_t d3, size_t d4, size_t elem_size, char *caller_file, int caller_line)
Allocate a 34D array and return ptr to it.
The data area is allocated in one block so it can also be treated as a 1-D array.
References ckd_calloc, E_FATAL.
SPHINXBASE_EXPORT void* __ckd_alloc_3d_ptr(size_t d1, size_t d2, size_t d3, void *store, size_t elem_size, char *caller_file, int caller_line)
Overlay a 3-D array over a previously allocated storage area.
SPHINXBASE_EXPORT void* __ckd_alloc_2d_ptr(size_t d1, size_t d2, void *store, size_t elem_size, char *caller_file, int caller_line)
Overlay a s-D array over a previously allocated storage area.
SPHINXBASE_EXPORT void ckd_free(void *ptr)
Test and free a 1-D array.
Referenced by yin_free, agc_free, subvecs_free, feat_set_subvecs, feat_array_free, feat_init, feat_s2mfc2feat, feat_free, feat_lda_transform, jsgf_grammar_free, ngram_model_free, ngram_score, ngram_probv, ngram_prob, ngram_iter, ngram_iter_free, ngram_model_read_classdef, ngram_model_set_read, ngram_model_set_iter_free, ngram_model_set_remove, ngram_model_set_map_words, bio_hdrarg_free, bio_fwrite, bio_read_wavfile, ckd_free_2d, ckd_free_3d, ckd_free_4d, cmd_ln_parse_file_r, cmd_ln_set_str_r, cmd_ln_free_r, glist_free, gnode_free, hash_table_lookup_bkey, hash_table_empty, hash_table_enter_bkey, hash_table_replace_bkey, hash_table_delete_bkey, hash_table_iter_free, hash_table_free, heap_destroy, huff_code_free, listelem_alloc_init, listelem_alloc_free, logmath_free, mmio_file_unmap, fopen_comp, fopen_compchk, lineiter_free, bit_encode_free, pctr_free, sbmsgq_init, sbmsgq_free, sbevent_init, sbevent_free, sbmtx_init, sbmtx_free, sbthread_free.
SPHINXBASE_EXPORT void ckd_free_2d(void *ptr)
Free a 2-D array (ptr) previously allocated by ckd_calloc_2d.
References ckd_free.
Referenced by yin_free, feat_array_free, feat_s2mfc2feat, feat_free, ngram_model_set_add, ngram_model_set_map_words.
SPHINXBASE_EXPORT void ckd_free_3d(void *ptr)
Free a 3-D array (ptr) previously allocated by ckd_calloc_3d.
References ckd_free.
Referenced by feat_free, feat_read_lda.
SPHINXBASE_EXPORT void ckd_free_4d(void *ptr)
Free a 4-D array (ptr) previously allocated by ckd_calloc_4d.
References ckd_free.