cmd_ln.c
typedef struct cmd_ln_val_s cmd_ln_val_t
cmd_ln_t* global_cmdln
Global command-line, for non-reentrant API.
static void arg_dump_r(cmd_ln_t *, FILE *, arg_t const *, int32)
static cmd_ln_t * parse_options(cmd_ln_t *, const arg_t *, int32, char *[], int32)
static int32 arg_strlen(const arg_t *defn, int32 *namelen, int32 *deflen)
static int32 cmp_name(const void *a, const void *b)
static const arg_t** arg_sort(const arg_t *defn, int32 n)
static size_t strnappend(char **dest, size_t *dest_allocation, const char *source, size_t n)
static size_t strappend(char **dest, size_t *dest_allocation, const char *source)
static char* arg_resolve_env(const char *str)
static char** parse_string_list(const char *str)
static cmd_ln_val_t* cmd_ln_val_init(int t, const char *str)
void cmd_ln_val_free(cmd_ln_val_t *val)
cmd_ln_t* cmd_ln_get(void)
Retrieve the global cmd_ln_t object used by non-re-entrant functions.
DeprecatedThis is deprecated in favor of the re-entrant API. global cmd_ln_t object.
void cmd_ln_appl_enter(int argc, char *argv[], const char *default_argfn, const arg_t *defn)
In: Number of actual arguments
DeprecatedThis is deprecated in favor of the re-entrant API.
References cmd_ln_print_help, E_INFO, cmd_ln_parse_file, E_INFOCONT, cmd_ln_parse.
void cmd_ln_appl_exit()
Finalization routine corresponding to cmd_ln_appl_enter().
DeprecatedThis is deprecated in favor of the re-entrant API.
References cmd_ln_free.
cmd_ln_t* cmd_ln_parse_r(cmd_ln_t *inout_cmdln, const arg_t *defn, int32 argc, char *argv[], int strict)
In/Out: Previous command-line to update, or NULL to create a new one.
Parse the given list of arguments (name-value pairs) according to the given definitions. Argument values can be retrieved in future using cmd_ln_access(). argv[0] is assumed to be the program name and skipped. Any unknown argument name causes a fatal error. The routine also prints the prevailing argument values (to stderr) after parsing.It is currently assumed that the strings in argv are allocated statically, or at least that they will be valid as long as the cmd_ln_t returned from this function. Unpredictable behaviour will result if they are freed or otherwise become invalidated. A cmd_ln_t containing the results of command line parsing, or NULL on failure.
References ckd_calloc, hash_table_new, hash_table_enter, E_ERROR, hash_table_lookup, cmd_ln_print_help_r, ARG_STRING, hash_table_replace, ARG_REQUIRED, hash_table_free, cmd_ln_free_r, cmd_ln_exists_r, cmd_ln_str_r, err_set_logfile, E_FATAL_SYSTEM, E_INFO, E_INFOCONT, err_get_logfp.
Referenced by cmd_ln_parse.
cmd_ln_t* cmd_ln_init(cmd_ln_t *inout_cmdln, const arg_t *defn, int32 strict,...)
Create a cmd_ln_t from NULL-terminated list of arguments.
This function creates a cmd_ln_t from a NULL-terminated list of argument strings. For example, to create the equivalent of passing "-hmm foodir -dsratio 2 -lm bar.lm" on the command-line:config = cmd_ln_init(NULL, defs, TRUE, "-hmm", "foodir", "-dsratio", "2", "-lm", "bar.lm", NULL);Note that for simplicity, all arguments are passed as strings, regardless of the actual underlying type. inout_cmdln Previous command-line to update, or NULL to create a new one. defn Array of argument name definitions, or NULL to allow any arguments. strict Whether to fail on duplicate or unknown arguments. A cmd_ln_t* containing the results of command line parsing, or NULL on failure.
References E_ERROR, ckd_calloc, ckd_salloc.
int cmd_ln_parse(const arg_t *defn, int32 argc, char *argv[], int strict)
In: Array of argument name definitions
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_parse_r(). 0 if successful, <0 if error.
References cmd_ln_parse_r, E_ERROR.
Referenced by cmd_ln_appl_enter.
cmd_ln_t* cmd_ln_parse_file_r(cmd_ln_t *inout_cmdln, const arg_t *defn, const char *filename, int32 strict)
In/Out: Previous command-line to update, or NULL to create a new one.
A cmd_ln_t containing the results of command line parsing, or NULL on failure.
References E_ERROR, ckd_calloc, ckd_realloc, ckd_salloc, E_WARN, ckd_free.
Referenced by cmd_ln_parse_file.
int cmd_ln_parse_file(const arg_t *defn, const char *filename, int32 strict)
In: Array of argument name definitions
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_parse_file_r().0 if successful, <0 on error.
References cmd_ln_parse_file_r.
Referenced by cmd_ln_appl_enter.
void cmd_ln_print_help_r(cmd_ln_t *cmdln, FILE *fp, arg_t const *defn)
Print a help message listing the valid argument names, and the associated attributes as given in defn.
fp output stream defn Array of argument name definitions.
Referenced by cmd_ln_parse_r.
int cmd_ln_exists_r(cmd_ln_t *cmdln, const char *name)
Re-entrant version of cmd_ln_exists().
True if the command line argument exists (i.e. it was one of the arguments defined in the call to cmd_ln_parse_r().
References hash_table_lookup.
Referenced by ngram_model_read, cmd_ln_parse_r.
anytype_t* cmd_ln_access_r(cmd_ln_t *cmdln, const char *name)
Access the generic type union for a command line argument.
References hash_table_lookup, E_ERROR.
Referenced by cmd_ln_str_r, cmd_ln_str_list_r, cmd_ln_int_r, cmd_ln_float_r, cmd_ln_set_str_r, cmd_ln_set_int_r, cmd_ln_set_float_r.
char const* cmd_ln_str_r(cmd_ln_t *cmdln, char const *name)
Retrieve a string from a command-line object.
The command-line object retains ownership of this string, so you should not attempt to free it manually. cmdln Command-line object. name the command-line flag to retrieve. the string value associated with name, or NULL if name does not exist. You must use cmd_ln_exists_r() to distinguish between cases where a value is legitimately NULL and where the corresponding flag is unknown.
References cmd_ln_access_r.
Referenced by cmd_ln_parse_r.
char const** cmd_ln_str_list_r(cmd_ln_t *cmdln, char const *name)
Retrieve an array of strings from a command-line object.
The command-line object retains ownership of this array, so you should not attempt to free it manually. cmdln Command-line object. name the command-line flag to retrieve. the array of strings associated with name, or NULL if name does not exist. You must use cmd_ln_exists_r() to distinguish between cases where a value is legitimately NULL and where the corresponding flag is unknown.
References cmd_ln_access_r.
long cmd_ln_int_r(cmd_ln_t *cmdln, char const *name)
Retrieve an integer from a command-line object.
cmdln Command-line object. name the command-line flag to retrieve. the integer value associated with name, or 0 if name does not exist. You must use cmd_ln_exists_r() to distinguish between cases where a value is legitimately zero and where the corresponding flag is unknown.
References cmd_ln_access_r.
double cmd_ln_float_r(cmd_ln_t *cmdln, char const *name)
Retrieve a floating-point number from a command-line object.
cmdln Command-line object. name the command-line flag to retrieve. the float value associated with name, or 0.0 if name does not exist. You must use cmd_ln_exists_r() to distinguish between cases where a value is legitimately zero and where the corresponding flag is unknown.
References cmd_ln_access_r.
void cmd_ln_set_str_r(cmd_ln_t *cmdln, char const *name, char const *str)
Set a string in a command-line object.
cmdln Command-line object. name The command-line flag to set. str String value to set. The command-line object does not retain ownership of this pointer.
References cmd_ln_access_r, E_ERROR, ckd_free, ckd_salloc.
void cmd_ln_set_int_r(cmd_ln_t *cmdln, char const *name, long iv)
Set an integer in a command-line object.
cmdln Command-line object. name The command-line flag to set. iv Integer value to set.
References cmd_ln_access_r, E_ERROR.
void cmd_ln_set_float_r(cmd_ln_t *cmdln, char const *name, double fv)
Set a floating-point number in a command-line object.
cmdln Command-line object. name The command-line flag to set. fv Integer value to set.
References cmd_ln_access_r, E_ERROR.
cmd_ln_t* cmd_ln_retain(cmd_ln_t *cmdln)
Retain ownership of a command-line argument set.
pointer to retained command-line argument set.
int cmd_ln_free_r(cmd_ln_t *cmdln)
Release a command-line argument set and all associated strings.
new reference count (0 if freed completely)
References hash_table_tolist, gnode_ptr, hash_entry_s::val, glist_free, hash_table_free, ckd_free.
Referenced by cmd_ln_parse_r, cmd_ln_free.
void cmd_ln_free(void)
Free the global command line, if any exists.
DeprecatedUse the re-entrant API instead.
References cmd_ln_free_r.
Referenced by cmd_ln_appl_exit.