cmd_ln.h
ARG_REQUIRED
Bit indicating a required argument.
Referenced by cmd_ln_parse_r.
ARG_INTEGER
Integer argument (optional).
ARG_FLOATING
Floating point argument (optional).
ARG_STRING
String argument (optional).
Referenced by cmd_ln_parse_r.
ARG_BOOLEAN
Boolean (true/false) argument (optional).
ARG_STRING_LIST
Boolean (true/false) argument (optional).
REQARG_INTEGER
Required integer argument.
REQARG_FLOATING
Required floating point argument.
REQARG_STRING
Required string argument.
REQARG_BOOLEAN
Required boolean argument.
ARG_INT32
DeprecatedUse ARG_INTEGER instead.
ARG_FLOAT32
DeprecatedUse ARG_FLOATING instead.
ARG_FLOAT64
DeprecatedUse ARG_FLOATING instead.
REQARG_INT32
DeprecatedUse REQARG_INTEGER instead.
REQARG_FLOAT32
DeprecatedUse REQARG_FLOATING instead.
REQARG_FLOAT64
DeprecatedUse REQARG_FLOATING instead.
ARG_STRINGIFY
Helper macro to stringify enums and other non-string values for default arguments.
ARG_STRINGIFY1
cmd_ln_boolean_r
Retrieve a boolean value from a command-line object.
cmd_ln_set_boolean_r
Set a boolean value in a command-line object.
cmd_ln_int32_r
cmd_ln_float32_r
cmd_ln_float64_r
cmd_ln_set_int32_r
cmd_ln_set_float32_r
cmd_ln_set_float64_r
cmd_ln_exists
Test the existence of a command-line argument in the global set of definitions.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_exists_r().True if the command line argument exists (i.e. it was one of the arguments defined in the call to cmd_ln_parse().
cmd_ln_access
Return a pointer to the previously parsed value for the given argument name.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_access_r().
cmd_ln_str
Retrieve a string from the global command line.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_str_r().
cmd_ln_str_list
Retrieve an array of strings in the global command line.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_str_list_r().
cmd_ln_int32
Retrieve a 32-bit integer from the global command line.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_int_r().
cmd_ln_float32
Retrieve a 32-bit float from the global command line.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_float_r().
cmd_ln_float64
Retrieve a 64-bit float from the global command line.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_float_r().
cmd_ln_boolean
Retrieve a boolean from the global command line.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_boolean_r().
cmd_ln_set_str
Set a string in the global command line.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_set_str_r().
cmd_ln_set_int32
Set a 32-bit integer value in the global command line.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_set_int_r().
cmd_ln_set_float32
Set a 32-bit float in the global command line.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_set_float_r().
cmd_ln_set_float64
Set a 64-bit float in the global command line.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_set_float_r().
cmd_ln_set_boolean
Set a boolean value in the global command line.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_set_boolean_r().
cmd_ln_print_help
Print a help message listing the valid argument names, and the associated attributes as given in defn.
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_print_help_r().
Referenced by cmd_ln_appl_enter.
typedef struct arg_s arg_t
typedef struct cmd_ln_s cmd_ln_t
SPHINXBASE_EXPORT cmd_ln_t* cmd_ln_init(cmd_ln_t *inout_cmdln, arg_t const *defn, int32 strict,...)
Create a cmd_ln_t from NULL-terminated list of arguments.
This function creates a cmd_ln_t from a NULL-terminated list of argument strings. For example, to create the equivalent of passing "-hmm foodir -dsratio 2 -lm bar.lm" on the command-line:config = cmd_ln_init(NULL, defs, TRUE, "-hmm", "foodir", "-dsratio", "2", "-lm", "bar.lm", NULL);Note that for simplicity, all arguments are passed as strings, regardless of the actual underlying type. inout_cmdln Previous command-line to update, or NULL to create a new one. defn Array of argument name definitions, or NULL to allow any arguments. strict Whether to fail on duplicate or unknown arguments. A cmd_ln_t* containing the results of command line parsing, or NULL on failure.
References ckd_calloc, ckd_salloc, E_ERROR.
SPHINXBASE_EXPORT cmd_ln_t* cmd_ln_retain(cmd_ln_t *cmdln)
Retain ownership of a command-line argument set.
pointer to retained command-line argument set.
SPHINXBASE_EXPORT int cmd_ln_free_r(cmd_ln_t *cmdln)
Release a command-line argument set and all associated strings.
new reference count (0 if freed completely)
References ckd_free, glist_free, gnode_ptr, hash_table_free, hash_table_tolist, hash_entry_s::val.
Referenced by cmd_ln_free, cmd_ln_parse_r.
SPHINXBASE_EXPORT cmd_ln_t* cmd_ln_parse_r(cmd_ln_t *inout_cmdln, arg_t const *defn, int32 argc, char *argv[], int32 strict)
In/Out: Previous command-line to update, or NULL to create a new one.
Parse the given list of arguments (name-value pairs) according to the given definitions. Argument values can be retrieved in future using cmd_ln_access(). argv[0] is assumed to be the program name and skipped. Any unknown argument name causes a fatal error. The routine also prints the prevailing argument values (to stderr) after parsing.It is currently assumed that the strings in argv are allocated statically, or at least that they will be valid as long as the cmd_ln_t returned from this function. Unpredictable behaviour will result if they are freed or otherwise become invalidated. A cmd_ln_t containing the results of command line parsing, or NULL on failure.
References ARG_REQUIRED, ARG_STRING, ckd_calloc, cmd_ln_exists_r, cmd_ln_free_r, cmd_ln_print_help_r, cmd_ln_str_r, E_ERROR, E_FATAL_SYSTEM, E_INFO, E_INFOCONT, err_get_logfp, err_set_logfile, hash_table_enter, hash_table_free, hash_table_lookup, hash_table_new, hash_table_replace.
Referenced by cmd_ln_parse.
SPHINXBASE_EXPORT cmd_ln_t* cmd_ln_parse_file_r(cmd_ln_t *inout_cmdln, arg_t const *defn, char const *filename, int32 strict)
In/Out: Previous command-line to update, or NULL to create a new one.
A cmd_ln_t containing the results of command line parsing, or NULL on failure.
References ckd_calloc, ckd_free, ckd_realloc, ckd_salloc, E_ERROR, E_WARN.
Referenced by cmd_ln_parse_file.
SPHINXBASE_EXPORT anytype_t* cmd_ln_access_r(cmd_ln_t *cmdln, char const *name)
Access the generic type union for a command line argument.
References hash_table_lookup, E_ERROR.
Referenced by cmd_ln_str_r, cmd_ln_str_list_r, cmd_ln_int_r, cmd_ln_float_r, cmd_ln_set_str_r, cmd_ln_set_int_r, cmd_ln_set_float_r.
SPHINXBASE_EXPORT char const* cmd_ln_str_r(cmd_ln_t *cmdln, char const *name)
Retrieve a string from a command-line object.
The command-line object retains ownership of this string, so you should not attempt to free it manually. cmdln Command-line object. name the command-line flag to retrieve. the string value associated with name, or NULL if name does not exist. You must use cmd_ln_exists_r() to distinguish between cases where a value is legitimately NULL and where the corresponding flag is unknown.
References cmd_ln_access_r.
Referenced by cmd_ln_parse_r.
SPHINXBASE_EXPORT char const** cmd_ln_str_list_r(cmd_ln_t *cmdln, char const *name)
Retrieve an array of strings from a command-line object.
The command-line object retains ownership of this array, so you should not attempt to free it manually. cmdln Command-line object. name the command-line flag to retrieve. the array of strings associated with name, or NULL if name does not exist. You must use cmd_ln_exists_r() to distinguish between cases where a value is legitimately NULL and where the corresponding flag is unknown.
References cmd_ln_access_r.
SPHINXBASE_EXPORT long cmd_ln_int_r(cmd_ln_t *cmdln, char const *name)
Retrieve an integer from a command-line object.
cmdln Command-line object. name the command-line flag to retrieve. the integer value associated with name, or 0 if name does not exist. You must use cmd_ln_exists_r() to distinguish between cases where a value is legitimately zero and where the corresponding flag is unknown.
References cmd_ln_access_r.
SPHINXBASE_EXPORT double cmd_ln_float_r(cmd_ln_t *cmdln, char const *name)
Retrieve a floating-point number from a command-line object.
cmdln Command-line object. name the command-line flag to retrieve. the float value associated with name, or 0.0 if name does not exist. You must use cmd_ln_exists_r() to distinguish between cases where a value is legitimately zero and where the corresponding flag is unknown.
References cmd_ln_access_r.
SPHINXBASE_EXPORT void cmd_ln_set_str_r(cmd_ln_t *cmdln, char const *name, char const *str)
Set a string in a command-line object.
cmdln Command-line object. name The command-line flag to set. str String value to set. The command-line object does not retain ownership of this pointer.
References ckd_free, ckd_salloc, cmd_ln_access_r, E_ERROR.
SPHINXBASE_EXPORT void cmd_ln_set_int_r(cmd_ln_t *cmdln, char const *name, long iv)
Set an integer in a command-line object.
cmdln Command-line object. name The command-line flag to set. iv Integer value to set.
References cmd_ln_access_r, E_ERROR.
SPHINXBASE_EXPORT void cmd_ln_set_float_r(cmd_ln_t *cmdln, char const *name, double fv)
Set a floating-point number in a command-line object.
cmdln Command-line object. name The command-line flag to set. fv Integer value to set.
References cmd_ln_access_r, E_ERROR.
SPHINXBASE_EXPORT int cmd_ln_exists_r(cmd_ln_t *cmdln, char const *name)
Re-entrant version of cmd_ln_exists().
True if the command line argument exists (i.e. it was one of the arguments defined in the call to cmd_ln_parse_r().
References hash_table_lookup.
Referenced by cmd_ln_parse_r, ngram_model_read.
SPHINXBASE_EXPORT void cmd_ln_print_help_r(cmd_ln_t *cmdln, FILE *fp, const arg_t *defn)
Print a help message listing the valid argument names, and the associated attributes as given in defn.
fp output stream defn Array of argument name definitions.
Referenced by cmd_ln_parse_r.
SPHINXBASE_EXPORT int32 cmd_ln_parse(const arg_t *defn, int32 argc, char *argv[], int32 strict)
In: Array of argument name definitions
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_parse_r(). 0 if successful, <0 if error.
References cmd_ln_parse_r, E_ERROR.
Referenced by cmd_ln_appl_enter.
SPHINXBASE_EXPORT int32 cmd_ln_parse_file(const arg_t *defn, char const *filename, int32 strict)
In: Array of argument name definitions
DeprecatedThis is deprecated in favor of the re-entrant API function cmd_ln_parse_file_r().0 if successful, <0 on error.
References cmd_ln_parse_file_r.
Referenced by cmd_ln_appl_enter.
SPHINXBASE_EXPORT void cmd_ln_appl_enter(int argc, char *argv[], char const *default_argfn, const arg_t *defn)
In: Number of actual arguments
DeprecatedThis is deprecated in favor of the re-entrant API.
References cmd_ln_parse, cmd_ln_parse_file, cmd_ln_print_help, E_INFO, E_INFOCONT.
SPHINXBASE_EXPORT void cmd_ln_appl_exit(void)
Finalization routine corresponding to cmd_ln_appl_enter().
DeprecatedThis is deprecated in favor of the re-entrant API.
References cmd_ln_free.
SPHINXBASE_EXPORT cmd_ln_t* cmd_ln_get(void)
Retrieve the global cmd_ln_t object used by non-re-entrant functions.
DeprecatedThis is deprecated in favor of the re-entrant API. global cmd_ln_t object.
SPHINXBASE_EXPORT void cmd_ln_free(void)
Free the global command line, if any exists.
DeprecatedUse the re-entrant API instead.
References cmd_ln_free_r.
Referenced by cmd_ln_appl_exit.