err.c
FILE* logfp
int logfp_disabled
int sphinx_debug_level
err_cb_f err_cb
void* err_user_data
void err_msg(err_lvl_t lvl, const char *path, long ln, const char *fmt,...)
void err_logfp_cb(void *user_data, err_lvl_t lvl, const char *fmt,...)
int err_set_logfile(const char *path)
Append all log messages to a given file.
Previous logging filehandle is closed (unless it was stdout or stderr). file File path to send log messages to 0 for success, <0 for failure (e.g. if file does not exist)
References err_get_logfp, err_set_logfp.
Referenced by cmd_ln_parse_r.
void err_set_logfp(FILE *stream)
Direct all logging to a given filehandle if default logfp callback is set.
logfp Filehandle to send log messages to, or NULL to disable logging.
Referenced by err_set_logfile.
FILE* err_get_logfp(void)
Get the current logging filehandle.
Current logging filehandle, NULL if logging is disabled. Initially it returns stderr
Referenced by cmd_ln_parse_r, err_set_logfile.
int err_set_debug_level(int level)
Set debugging verbosity level.
Note that debugging messages are only enabled when compiled with -DDEBUG. level Verbosity level to set, or 0 to disable debug messages.
int err_get_debug_level(void)
Get debugging verbosity level.
Note that debugging messages are only enabled when compiled with -DDEBUG.
void err_set_callback(err_cb_f cb, void *user_data)
Sets function to output error messages.
Use it to redirect the logging to your application. By default the handler which dumps messages to stderr is set. - callback to pass messages too.