feat.c
FEAT_VERSION
FEAT_DCEP_WIN
cep_dump_dbg
feat_print_dbg
int32** parse_subvecs(char const *str)
Parse subvector specification string.
Format of specification: '/' separated list of subvectors each subvector is a ',' separated list of subranges each subrange is a single<number> or <number>-<number> (inclusive), where <number> is a feature vector dimension specifier. E.g., "24,0-11/25,12-23/26,27-38" has: 3 subvectors the 1st subvector has feature dims: 24, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, and 11. etc. str subvector specification string. allocated 2-D array of subvector specs (free with subvecs_free()). If there are N subvectors specified, subvec[N] = NULL; and each subvec[0]..subvec[N-1] is -1 terminated vector of feature dims.
References E_FATAL, glist_add_int32, glist_add_ptr, glist_count, ckd_calloc, gnode_ptr, glist_free.
void subvecs_free(int32 **subvecs)
Free array of subvector specs.
References ckd_free.
Referenced by feat_set_subvecs, feat_free.
int feat_set_subvecs(feat_t *fcb, int32 **subvecs)
Add a subvector specification to the feature module.
The subvector splitting will be performed after dynamic feature computation, CMN, AGC, and any LDA transformation. The number of streams in the dynamic feature type must be one, as with LDA.After adding a subvector specification, the output of feature computation will be split into multiple subvectors, and feat_array_alloc() will allocate pointers accordingly. The number of streams will remain the fcb the feature descriptor. subvecs subvector specification. This pointer is retained by the feat_t and should not be freed manually. 0 for success or -1 if the subvector specification was invalid.
References subvecs_free, ckd_free, E_ERROR, feat_dimension, ckd_calloc.
static void feat_subvec_project(feat_t *fcb, mfcc_t ***inout_feat, uint32 nfr)
Project feature components to subvectors (if any).
mfcc_t*** feat_array_alloc(feat_t *fcb, int32 nfr)
In: Descriptor from feat_init(), used to obtain number of streams and stream sizes
The returned value is the mfcc_t ***data array, organized as follows: data[0][0] = frame 0 stream 0 vector, data[0][1] = frame 0 stream 1 vector, ...data[1][0] = frame 1 stream 0 vector, data[0][1] = frame 1 stream 1 vector, ...data[2][0] = frame 2 stream 0 vector, data[0][1] = frame 2 stream 1 vector, ...... NOTE: For I/O convenience, the entire data area is allocated as one contiguous block. pointer to the allocated space if successful, NULL if any error.
References feat_dimension, ckd_calloc_2d, feat_dimension1, ckd_calloc, feat_dimension2.
Referenced by feat_array_realloc.
mfcc_t*** feat_array_realloc(feat_t *fcb, mfcc_t ***old_feat, int32 ofr, int32 nfr)
In: Descriptor from feat_init(), used to obtain number of streams and stream sizes
Requires us to know the old size
References feat_dimension, feat_array_alloc, feat_array_free.
void feat_array_free(mfcc_t ***feat)
Free a buffer allocated with feat_array_alloc()
References ckd_free, ckd_free_2d.
Referenced by feat_array_realloc.
static void feat_s2_4x_cep2feat(feat_t *fcb, mfcc_t **mfc, mfcc_t **feat)
static void feat_s3_1x39_cep2feat(feat_t *fcb, mfcc_t **mfc, mfcc_t **feat)
static void feat_s3_cep(feat_t *fcb, mfcc_t **mfc, mfcc_t **feat)
static void feat_s3_cep_dcep(feat_t *fcb, mfcc_t **mfc, mfcc_t **feat)
static void feat_1s_c_d_dd_cep2feat(feat_t *fcb, mfcc_t **mfc, mfcc_t **feat)
static void feat_1s_c_d_ld_dd_cep2feat(feat_t *fcb, mfcc_t **mfc, mfcc_t **feat)
static void feat_copy(feat_t *fcb, mfcc_t **mfc, mfcc_t **feat)
feat_t* feat_init(char const *type, cmn_type_t cmn, int32 varnorm, agc_type_t agc, int32 breport, int32 cepsize)
In: Type of feature stream
One-time only initialization at the beginning of the program. Input type is a string defining the kind of input->feature conversion desired: "s2_4x": s2mfc->Sphinx-II 4-feature stream,"1s_c_d_dd": s2mfc->Sphinx 3.x single feature stream,"s3_1x39": s2mfc->Sphinx 3.0 single feature stream,"n1,n2,n3,...": Explicit feature vector layout spec. with comma-separated feature stream lengths. In this case, the input data is already in the feature format and there is no conversion necessary. (feat_t *) descriptor if successful, NULL if error. Caller must not directly modify the contents of the returned value.
References E_INFO, cmn_type_str, agc_type_str, ckd_calloc, ckd_salloc, E_ERROR, ckd_free, feat_cepsize, E_FATAL, cmn, agc_init, agc_emax_set, ckd_calloc_2d, feat_window_size.
void feat_print(feat_t *fcb, mfcc_t ***feat, int32 nfr, FILE *fp)
In: Descriptor from feat_init()
References feat_dimension1, feat_dimension2.
static void feat_cmn(feat_t *fcb, mfcc_t **mfc, int32 nfr, int32 beginutt, int32 endutt)
static void feat_agc(feat_t *fcb, mfcc_t **mfc, int32 nfr, int32 beginutt, int32 endutt)
static void feat_compute_utt(feat_t *fcb, mfcc_t **mfc, int32 nfr, int32 win, mfcc_t ***feat)
static int32 feat_s2mfc_read_norm_pad(feat_t *fcb, char *file, int32 win, int32 sf, int32 ef, mfcc_t ***out_mfc, int32 maxfr, int32 cepsize)
Read Sphinx-II format mfc file (s2mfc = Sphinx-II format MFC data).
If out_mfc is NULL, no actual reading will be done, and the number of frames (plus padding) that would be read is returned.It's important that normalization is done before padding because frames outside the data we are interested in shouldn't be taken into normalization stats.# frames read (plus padding) if successful, -1 if error (e.g., mfc array too small).
int32 feat_s2mfc2feat(feat_t *fcb, const char *file, const char *dir, const char *cepext, int32 sf, int32 ef, mfcc_t ***feat, int32 maxfr)
In: Descriptor from feat_init()
Feature vectors are computed for the entire segment specified, by including additional surrounding or padding frames to accommodate the feature windows.Number of frames of feature vectors computed if successful; -1 if any error. If feat is NULL, then no actual computation will be done, and the number of frames which must be allocated will be returned. A note on how the file path is constructed: If the control file already specifies extension or absolute path, then these are not applied. The default extension is defined by the application.
References E_ERROR, E_INFO, ckd_calloc, ckd_realloc, feat_window_size, ckd_free, ckd_free_2d.
static int32 feat_s2mfc2feat_block_utt(feat_t *fcb, mfcc_t **uttcep, int32 nfr, mfcc_t ***ofeat)
int32 feat_s2mfc2feat_live(feat_t *fcb, mfcc_t **uttcep, int32 *inout_ncep, int32 beginutt, int32 endutt, mfcc_t ***ofeat)
In: Descriptor from feat_init()
This function computes features for blocks of incoming data. It retains an internal buffer for computing deltas, which means that the number of output frames will not necessarily equal the number of input frames.It is very important to realize that the number of output frames can be greater than the number of input frames, specifically when endutt is true. It is guaranteed to never exceed *inout_ncep + feat_window_size(fcb). You MUST have allocated at least that many frames in ofeat, or you will experience a buffer overflow.If beginutt and endutt are both true, CMN_CURRENT and AGC_MAX will be done. Otherwise only CMN_PRIOR and AGC_EMAX will be done.If beginutt is false, endutt is true, and the number of input frames exceeds the input size, then end-of-utterance processing won't actually be done. This condition can easily be checked, because *inout_ncep will equal the return value on exit, and will also be smaller than the value of *inout_ncep on entry.The number of output frames actually computed.
References feat_window_size, feat_cepsize, feat_lda_transform.
feat_t* feat_retain(feat_t *f)
Retain ownership of feat_t.
pointer to retained feat_t.
int feat_free(feat_t *f)
In: feat_t
new reference count (0 if freed)
References ckd_free_2d, ckd_free, ckd_free_3d, subvecs_free, agc_free.
void feat_report(feat_t *f)
In: feat_t
References E_INFO_NOFN, E_INFOCONT.