glist.c
glist_t glist_add_ptr(glist_t g, void *ptr)
a link list
Return the new list thus formed. g may be NULL to indicate an initially empty list.
References ckd_calloc, gnode_s::next.
Referenced by parse_subvecs, jsgf_grammar_new, ngram_model_set_read, hash_table_tolist.
glist_t glist_add_int32(glist_t g, int32 val)
a link list
References ckd_calloc, gnode_s::next.
Referenced by parse_subvecs.
glist_t glist_add_uint32(glist_t g, uint32 val)
a link list
References ckd_calloc, gnode_s::next.
glist_t glist_add_float32(glist_t g, float32 val)
a link list
References ckd_calloc, gnode_s::next.
Referenced by ngram_model_add_class.
glist_t glist_add_float64(glist_t g, float64 val)
a link list
References ckd_calloc, gnode_s::next.
void glist_free(glist_t g)
Free the given generic list; user-defined data contained within is not automatically freed.
The caller must have done that already.
References gnode_s::next, ckd_free.
Referenced by parse_subvecs, jsgf_grammar_free, ngram_model_add_class, ngram_model_read_classdef, ngram_model_set_read, cmd_ln_free_r, listelem_alloc_free.
int32 glist_count(glist_t g)
input link list
the number of elements in the given glist_t
References gnode_s::next.
Referenced by parse_subvecs, ngram_model_set_read.
gnode_t* glist_tail(glist_t g)
Return the last node in the given list.
References gnode_s::next.
glist_t glist_reverse(glist_t g)
input link list
(glist_add() adds to the head; one might ultimately want the reverse of that.) NOTE: The list is reversed "in place"; i.e., no new memory is allocated. : The head of the new list.
References gnode_s::next.
Referenced by jsgf_grammar_new, ngram_model_add_class, ngram_model_set_read.
gnode_t* glist_insert_ptr(gnode_t *gn, void *ptr)
a generic node which ptr will be inserted after it
gn cannot be NULL. Return ptr to the newly created gnode_t.
References ckd_calloc, gnode_s::next.
gnode_t* glist_insert_int32(gnode_t *gn, int32 val)
a generic node which a value will be inserted after it
References ckd_calloc, gnode_s::next.
gnode_t* glist_insert_uint32(gnode_t *gn, uint32 val)
a generic node which a value will be inserted after it
References ckd_calloc, gnode_s::next.
gnode_t* glist_insert_float32(gnode_t *gn, float32 val)
a generic node which a value will be inserted after it
References ckd_calloc, gnode_s::next.
gnode_t* glist_insert_float64(gnode_t *gn, float64 val)
a generic node which a value will be inserted after it
References ckd_calloc, gnode_s::next.
gnode_t* gnode_free(gnode_t *gn, gnode_t *pred)
Free the given node, gn, of a glist, pred being its predecessor in the list.
Return ptr to the next node in the list after the freed node.
References gnode_s::next, ckd_free.