hash_table.c
const int32 prime[][]
static int32 prime_size(int32 size)
This function returns a very large prime.
hash_table_t* hash_table_new(int32 size, int32 casearg)
In: Expected number of entries in the table
Case sensitivity of hash keys applies to 7-bit ASCII characters only, and is not locale-dependent. handle to allocated hash table.
References ckd_calloc, hash_table_t::size, hash_table_t::nocase.
Referenced by jsgf_grammar_new, ngram_model_casefold, ngram_model_read_classdef, ngram_model_set_read, cmd_ln_parse_r, huff_code_read.
static uint32 key2hash(hash_table_t *h, const char *key)
static char* makekey(uint8 *data, int32 len, char *key)
static int32 keycmp_nocase(hash_entry_t *entry, const char *key)
static int32 keycmp_case(hash_entry_t *entry, const char *key)
static hash_entry_t* lookup(hash_table_t *h, uint32 hash, const char *key, size_t len)
int32 hash_table_lookup(hash_table_t *h, const char *key, void **val)
In: Handle of hash table being searched
0 if key found in hash table, else -1.
References hash_entry_s::val.
Referenced by jsgf_get_rule, ngram_model_set_read, cmd_ln_parse_r, cmd_ln_exists_r, cmd_ln_access_r, hash_table_lookup_int32, huff_code_encode_str.
int32 hash_table_lookup_int32(hash_table_t *h, const char *key, int32 *val)
In: Handle of hash table being searched
This function is the clean way to do this and avoid compiler warnings on 64-bit platforms.
References hash_table_lookup.
Referenced by ngram_unknown_wid, ngram_wid.
int32 hash_table_lookup_bkey(hash_table_t *h, const char *key, size_t len, void **val)
In: Handle of hash table being searched
So the key string is a binary key (or bkey). Hash tables containing such keys should be created with the HASH_CASE_YES option. Otherwise, the results are unpredictable.
References ckd_free, hash_entry_s::val.
Referenced by hash_table_lookup_bkey_int32, huff_code_encode_int.
int32 hash_table_lookup_bkey_int32(hash_table_t *h, const char *key, size_t len, int32 *val)
In: Handle of hash table being searched
This function is the clean way to do this and avoid compiler warnings on 64-bit platforms.
References hash_table_lookup_bkey.
static void* enter(hash_table_t *h, uint32 hash, const char *key, size_t len, void *val, int32 replace)
static void* delete(hash_table_t *h, uint32 hash, const char *key, size_t len)
void hash_table_empty(hash_table_t *h)
In: Handle of hash table
References hash_table_t::size, hash_entry_s::next, ckd_free, hash_table_t::inuse.
Referenced by ngram_model_set_map_words.
void* hash_table_enter(hash_table_t *h, const char *key, void *val)
In: Handle of hash table in which to create entry
If key doesn't already exist in hash table, the addition is successful, and the return value is val. But if key already exists, return its existing associated value. (The hash table is unchanged; it is up to the caller to resolve the conflict.)
Referenced by cmd_ln_parse_r, huff_code_read.
void* hash_table_replace(hash_table_t *h, const char *key, void *val)
In: Handle of hash table in which to create entry
If the key already exists, its value is replaced with the given value, and the previous value is returned, otherwise val is returned.A very important but subtle point: The key pointer in the hash table is replaced with the pointer passed to this function. In general you should always pass a pointer to hash_table_enter() whose lifetime matches or exceeds that of the hash table. In some rare cases it is convenient to initially enter a value with a short-lived key, then later replace that with a long-lived one. This behaviour allows this to happen.
Referenced by cmd_ln_parse_r.
void* hash_table_delete(hash_table_t *h, const char *key)
In: Handle of hash table in which a key will be deleted
Return the value associated with the key (NULL if it did not exist)
void* hash_table_enter_bkey(hash_table_t *h, const char *key, size_t len, void *val)
In: Handle of hash table in which to create entry
So the key string is a binary key (or bkey). Hash tables containing such keys should be created with the HASH_CASE_YES option. Otherwise, the results are unpredictable.
References ckd_free.
Referenced by huff_code_read.
void* hash_table_replace_bkey(hash_table_t *h, const char *key, size_t len, void *val)
In: Handle of hash table in which to create entry
So the key string is a binary key (or bkey). Hash tables containing such keys should be created with the HASH_CASE_YES option. Otherwise, the results are unpredictable.
References ckd_free.
void* hash_table_delete_bkey(hash_table_t *h, const char *key, size_t len)
In: Handle of hash table in which a key will be deleted
So the key string is a binary key (or bkey). Hash tables containing such keys should be created with the HASH_CASE_YES option. Otherwise, the results are unpredictable.
References ckd_free.
void hash_table_display(hash_table_t *h, int32 showdisplay)
In: Hash table to display
Currently, it will only works for situation where hash_enter was used to enter the keys.
References hash_table_t::size, hash_entry_s::len, hash_entry_s::val, hash_entry_s::next.
glist_t hash_table_tolist(hash_table_t *h, int32 *count)
In: Hash table from which list is to be generated
Return the list.
References hash_table_t::size, glist_add_ptr, hash_entry_s::next.
Referenced by ngram_model_read_classdef, ngram_model_set_read, cmd_ln_free_r.
hash_iter_t* hash_table_iter(hash_table_t *h)
Start iterating over key-value pairs in a hash table.
References ckd_calloc, hash_iter_s::ht, hash_table_iter_next.
Referenced by jsgf_grammar_free, jsgf_rule_iter.
hash_iter_t* hash_table_iter_next(hash_iter_t *itor)
Get the next key-value pair in iteration.
This function automatically frees the iterator object upon reaching the final entry.the next entry in the hash table, or NULL if done.
References hash_iter_s::ent, hash_entry_s::next, hash_iter_s::idx, hash_iter_s::ht, hash_table_t::size, hash_table_iter_free.
Referenced by jsgf_grammar_free, hash_table_iter.
void hash_table_iter_free(hash_iter_t *itor)
Delete an unfinished iterator.
References ckd_free.
Referenced by hash_table_iter_next.
void hash_table_free(hash_table_t *h)
In: Handle of hash table to free
References hash_table_t::size, hash_entry_s::next, ckd_free.
Referenced by jsgf_grammar_free, ngram_model_free, ngram_model_casefold, ngram_model_read_classdef, ngram_model_set_read, cmd_ln_parse_r, cmd_ln_free_r, huff_code_free.