heap.c
typedef struct heapnode_s heapnode_t
One node on the heap.
heap_t* heap_new(void)
Allocate a new heap and return handle to it.
References ckd_calloc.
Referenced by huff_code_build_int, huff_code_build_str.
static heapnode_t* subheap_insert(heapnode_t *root, void *data, int32 val)
int heap_insert(heap_t *heap, void *data, int32 val)
In: Heap into which item is to be inserted
Return value: 0 if successful, -1 otherwise.
Referenced by huff_code_build_int, huff_code_build_str.
static heapnode_t* subheap_pop(heapnode_t *root)
int heap_pop(heap_t *heap, void **data, int32 *val)
Like heap_top but also pop the top item off the heap.
References heapnode_s::data, heapnode_s::val.
Referenced by heap_destroy.
int heap_top(heap_t *heap, void **data, int32 *val)
In: Heap whose topmost item is to be returned
Return value: 1 if heap is not empty and the topmost value is returned; 0 if heap is empty; -1 if some error occurred.
References heapnode_s::data, heapnode_s::val.
static int heap_remove_one(heap_t *heap, heapnode_t *top, void *data)
int heap_remove(heap_t *heap, void *data)
Remove an item from the heap.
size_t heap_size(heap_t *heap)
Return the number of items in the heap.
References heapnode_s::nr.
int heap_destroy(heap_t *heap)
Destroy the given heap; free the heap nodes.
NOTE: Data pointers in the nodes are NOT freed. Return value: 0 if successful, -1 otherwise.
References heap_pop, ckd_free.
Referenced by huff_code_build_int, huff_code_build_str.