huff_code.c
@2
typedef struct huff_node_s huff_node_t
typedef struct huff_codeword_s huff_codeword_t
static huff_node_t* huff_node_new_int(int32 val)
static huff_node_t* huff_node_new_str(char const *val)
static huff_node_t* huff_node_new_parent(huff_node_t *l, huff_node_t *r)
static void huff_node_free_int(huff_node_t *root)
static void huff_node_free_str(huff_node_t *root, int freestr)
static huff_node_t* huff_code_build_tree(heap_t *q)
static void huff_code_canonicalize(huff_code_t *hc, huff_node_t *root)
huff_code_t* huff_code_build_int(int32 const *values, int32 const *frequencies, int nvals)
Create a codebook from 32-bit integer data.
References ckd_calloc, heap_new, heap_insert, heap_destroy, E_ERROR, huff_code_free.
huff_code_t* huff_code_build_str(char *const *values, int32 const *frequencies, int nvals)
Create a codebook from string data.
References ckd_calloc, heap_new, heap_insert, heap_destroy, E_ERROR, huff_code_free.
huff_code_t* huff_code_read(FILE *infh)
Read a codebook from a file.
References ckd_calloc, hash_table_new, hash_table_enter_bkey, fread_line, hash_table_enter, huff_code_free.
int huff_code_write(huff_code_t *hc, FILE *outfh)
Write a codebook to a file.
int huff_code_dump_codebits(FILE *dumpfh, uint32 nbits, uint32 codeword)
int huff_code_dump(huff_code_t *hc, FILE *dumpfh)
Print a codebook to a file as text (for debugging)
huff_code_t* huff_code_retain(huff_code_t *hc)
Retain a pointer to a Huffman codec object.
int huff_code_free(huff_code_t *hc)
Release a pointer to a Huffman codec object.
References ckd_free, hash_table_free.
Referenced by huff_code_build_int, huff_code_build_str, huff_code_read.
FILE* huff_code_attach(huff_code_t *hc, FILE *fh, char const *mode)
Attach a Huffman codec to a file handle for input/output.
References huff_code_detach, bit_encode_attach.
FILE* huff_code_detach(huff_code_t *hc)
Detach a Huffman codec from its file handle.
References bit_encode_flush, bit_encode_free.
Referenced by huff_code_attach.
int huff_code_encode_int(huff_code_t *hc, int32 sym, uint32 *outcw)
Encode an integer, writing it to the file handle, if any.
References hash_table_lookup_bkey, bit_encode_write_cw.
int huff_code_encode_str(huff_code_t *hc, char const *sym, uint32 *outcw)
Encode a string, writing it to the file handle, if any.
References hash_table_lookup, bit_encode_write_cw.
static huff_codeword_t* huff_code_decode_data(huff_code_t *hc, char const **inout_data, size_t *inout_data_len, int *inout_offset)
static huff_codeword_t* huff_code_decode_fh(huff_code_t *hc)
int huff_code_decode_int(huff_code_t *hc, int *outval, char const **inout_data, size_t *inout_data_len, int *inout_offset)
Decode an integer, reading it from the file if no data given.
char const* huff_code_decode_str(huff_code_t *hc, char const **inout_data, size_t *inout_data_len, int *inout_offset)
Decode a string, reading it from the file if no data given.