huff_code.h
typedef struct huff_code_s huff_code_t
SPHINXBASE_EXPORT huff_code_t* huff_code_build_int(int32 const *values, int32 const *frequencies, int nvals)
Create a codebook from 32-bit integer data.
References ckd_calloc, heap_new, heap_insert, heap_destroy, E_ERROR, huff_code_free.
SPHINXBASE_EXPORT huff_code_t* huff_code_build_str(char *const *values, int32 const *frequencies, int nvals)
Create a codebook from string data.
References ckd_calloc, heap_new, heap_insert, heap_destroy, E_ERROR, huff_code_free.
SPHINXBASE_EXPORT huff_code_t* huff_code_read(FILE *infh)
Read a codebook from a file.
References ckd_calloc, hash_table_new, hash_table_enter_bkey, fread_line, hash_table_enter, huff_code_free.
SPHINXBASE_EXPORT int huff_code_write(huff_code_t *hc, FILE *outfh)
Write a codebook to a file.
SPHINXBASE_EXPORT int huff_code_dump(huff_code_t *hc, FILE *dumpfh)
Print a codebook to a file as text (for debugging)
SPHINXBASE_EXPORT huff_code_t* huff_code_retain(huff_code_t *hc)
Retain a pointer to a Huffman codec object.
SPHINXBASE_EXPORT int huff_code_free(huff_code_t *hc)
Release a pointer to a Huffman codec object.
References ckd_free, hash_table_free.
Referenced by huff_code_build_int, huff_code_build_str, huff_code_read.
SPHINXBASE_EXPORT FILE* huff_code_attach(huff_code_t *hc, FILE *fh, char const *mode)
Attach a Huffman codec to a file handle for input/output.
References huff_code_detach, bit_encode_attach.
SPHINXBASE_EXPORT FILE* huff_code_detach(huff_code_t *hc)
Detach a Huffman codec from its file handle.
References bit_encode_flush, bit_encode_free.
Referenced by huff_code_attach.
SPHINXBASE_EXPORT int huff_code_encode_int(huff_code_t *hc, int32 sym, uint32 *outcw)
Encode an integer, writing it to the file handle, if any.
References hash_table_lookup_bkey, bit_encode_write_cw.
SPHINXBASE_EXPORT int huff_code_encode_str(huff_code_t *hc, char const *sym, uint32 *outcw)
Encode a string, writing it to the file handle, if any.
References hash_table_lookup, bit_encode_write_cw.
SPHINXBASE_EXPORT int huff_code_decode_int(huff_code_t *hc, int *outval, char const **inout_data, size_t *inout_data_len, int *inout_offset)
Decode an integer, reading it from the file if no data given.
SPHINXBASE_EXPORT char const* huff_code_decode_str(huff_code_t *hc, char const **inout_data, size_t *inout_data_len, int *inout_offset)
Decode a string, reading it from the file if no data given.