logmath.c
logmath_t* logmath_init(float64 base, int shift, int use_table)
Initialize a log math computation table.
base The base B in which computation is to be done. shift Log values are shifted right by this many bits. use_table Whether to use an add table or not The newly created log math table.
References E_ERROR, ckd_calloc, logadd_s::shift, logadd_s::width, logadd_s::table, logadd_s::table_size.
Referenced by jsgf_write_fsg.
logmath_t* logmath_read(const char *file_name)
Memory-map (or read) a log table from a file.
References E_INFO, E_ERROR_SYSTEM, bio_readhdr, E_ERROR, ckd_calloc, logadd_s::shift, logadd_s::width, atof_c, bio_hdrarg_free, bio_fread, logadd_s::table_size, E_WARN, mmio_file_read, logadd_s::table, mmio_file_ptr, bio_verify_chksum, logmath_free.
int32 logmath_write(logmath_t *lmath, const char *file_name)
Write a log table to a file.
References logadd_s::table, E_ERROR, E_INFO, E_ERROR_SYSTEM, logadd_s::width, logadd_s::shift, bio_fwrite, logadd_s::table_size.
logmath_t* logmath_retain(logmath_t *lmath)
Retain ownership of a log table.
pointer to retained log table.
int logmath_free(logmath_t *lmath)
Free a log table.
new reference count (0 if freed completely)
References mmio_file_unmap, ckd_free, logadd_s::table.
Referenced by jsgf_write_fsg, logmath_read.
int32 logmath_get_table_shape(logmath_t *lmath, uint32 *out_size, uint32 *out_width, uint32 *out_shift)
Get the log table size and dimensions.
References logadd_s::table_size, logadd_s::width, logadd_s::shift.
float64 logmath_get_base(logmath_t *lmath)
Get the log base.
Referenced by ngram_model_set_init.
int logmath_get_zero(logmath_t *lmath)
Get the smallest possible value represented in this base.
int logmath_get_width(logmath_t *lmath)
Get the width of the values in a log table.
References logadd_s::width.
int logmath_get_shift(logmath_t *lmath)
Get the shift of the values in a log table.
References logadd_s::shift.
Referenced by ngram_model_set_init.
int logmath_add(logmath_t *lmath, int logb_x, int logb_y)
Add two values in log space (i.e.
return log(exp(p)+exp(q)))
References LOGMATH_TABLE, logadd_s::table, logmath_add_exact, logadd_s::table_size, logadd_s::width.
int logmath_add_exact(logmath_t *lmath, int logb_p, int logb_q)
Add two values in log space exactly and slowly (without using add table).
References logmath_log, logmath_exp.
Referenced by logmath_add.
int logmath_log(logmath_t *lmath, float64 p)
Convert linear floating point number to integer log in base B.
References logadd_s::shift.
Referenced by ngram_model_add_word, ngram_model_add_class_word, ngram_model_set_init, ngram_model_set_interp, ngram_model_set_add, ngram_model_set_remove, logmath_add_exact.
float64 logmath_exp(logmath_t *lmath, int logb_p)
Convert integer log in base B to linear floating point.
References logadd_s::shift.
Referenced by ngram_model_set_remove, logmath_add_exact.
int logmath_ln_to_log(logmath_t *lmath, float64 log_p)
Convert natural log (in floating point) to integer log in base B.
References logadd_s::shift.
float64 logmath_log_to_ln(logmath_t *lmath, int logb_p)
Convert integer log in base B to natural log (in floating point).
References logadd_s::shift.
int logmath_log10_to_log(logmath_t *lmath, float64 log_p)
Convert base 10 log (in floating point) to integer log in base B.
References logadd_s::shift.
float64 logmath_log_to_log10(logmath_t *lmath, int logb_p)
Convert integer log in base B to base 10 log (in floating point).
References logadd_s::shift.