mmio.c
mmio_file_t* mmio_file_read(const char *filename)
Memory-map a file for reading.
a mmio_file_t * or NULL for failure.
References E_ERROR_SYSTEM, ckd_calloc.
Referenced by logmath_read.
void mmio_file_unmap(mmio_file_t *mf)
Unmap a file, releasing memory associated with it.
References E_ERROR_SYSTEM, ckd_free.
Referenced by logmath_free.
void* mmio_file_ptr(mmio_file_t *mf)
Get a pointer to the memory mapped for a file.
Referenced by logmath_read.