ngram_model.c
ngram_file_type_t ngram_file_name_to_type(const char *file_name)
Guess the file type for an N-Gram model from the filename.
the guessed file type, or NGRAM_INVALID if none could be guessed.
References NGRAM_INVALID, strcmp_nocase, strncmp_nocase, NGRAM_ARPA, NGRAM_DMP.
Referenced by ngram_model_write.
ngram_file_type_t ngram_str_to_type(const char *str_name)
Get the N-Gram file type from a string.
file type, or NGRAM_INVALID if no such file type exists.
References strcmp_nocase, NGRAM_ARPA, NGRAM_DMP, NGRAM_INVALID.
char const* ngram_type_to_str(int type)
Get the canonical name for an N-Gram file type.
read-only string with the name for this file type, or NULL if no such type exists.
References NGRAM_ARPA, NGRAM_DMP.
ngram_model_t* ngram_model_read(cmd_ln_t *config, const char *file_name, ngram_file_type_t file_type, logmath_t *lmath)
Read an N-Gram model from a file on disk.
config Optional pointer to a set of command-line arguments. Recognized arguments are: -mmap (boolean) whether to use memory-mapped I/O-lw (float32) language weight to apply to the model-wip (float32) word insertion penalty to apply to the model-uw (float32) unigram weight to apply to the model file_name path to the file to read. file_type type of the file, or NGRAM_AUTO to determine automatically. lmath Log-math parameters to use for probability calculations. Ownership of this object is assumed by the newly created ngram_model_t, and you should not attempt to free it manually. If you wish to reuse it elsewhere, you must retain it with logmath_retain(). newly created ngram_model_t.
References NGRAM_AUTO, NGRAM_ARPA, NGRAM_DMP, E_ERROR, cmd_ln_exists_r, ngram_model_apply_weights.
Referenced by ngram_model_set_read.
int ngram_model_write(ngram_model_t *model, const char *file_name, ngram_file_type_t file_type)
Write an N-Gram model to disk.
0 for success, <0 on error
References NGRAM_AUTO, ngram_file_name_to_type, NGRAM_INVALID, NGRAM_ARPA, NGRAM_DMP, E_ERROR.
int32 ngram_model_init(ngram_model_t *base, ngram_funcs_t *funcs, logmath_t *lmath, int32 n, int32 n_unigram)
Initialize the base ngram_model_t structure.
ngram_model_t* ngram_model_retain(ngram_model_t *model)
Retain ownership of an N-Gram model.
Pointer to retained model.
References ngram_model_s::refcount.
Referenced by ngram_model_set_init.
void ngram_model_flush(ngram_model_t *model)
Flush any cached N-Gram information.
Some types of models cache trigram or other N-Gram information to speed repeated access to N-Grams with shared histories. This function flushes the cache so as to avoid dynamic memory leaks.
References ngram_model_s::funcs, ngram_funcs_s::flush.
int ngram_model_free(ngram_model_t *model)
Release memory associated with an N-Gram model.
new reference count (0 if freed completely)
References ngram_model_s::refcount, ngram_model_s::funcs, ngram_funcs_s::free, ngram_model_s::writable, ngram_model_s::n_words, ckd_free, ngram_model_s::word_str, ngram_model_s::n_classes, ngram_model_s::classes, ngram_class_s::n_words, ngram_class_s::start_wid, ngram_class_s::n_hash, ngram_class_s::ngram_hash_s::wid, hash_table_free, ngram_model_s::wid, ngram_model_s::n_counts.
Referenced by ngram_model_set_read.
int ngram_model_casefold(ngram_model_t *model, int kase)
Case-fold word strings in an N-Gram model.
WARNING: This is not Unicode aware, so any non-ASCII characters will not be converted.
References ngram_model_s::writable, hash_table_new, ngram_model_s::n_words, ngram_model_s::word_str, ckd_salloc, ucase, lcase, hash_table_enter_int32, E_WARN, hash_table_free, ngram_model_s::wid.
int ngram_model_recode(ngram_model_t *model, const char *from, const char *to)
Re-encode word strings in an N-Gram model.
Character set names are the same as those passed to iconv(1). If your system does not have iconv, this function may fail. Also, because all file formats consist of 8-bit character streams, attempting to convert to or from UTF-16 (or any other encoding which contains null bytes) is a recipe for total desaster.We have no interest in supporting UTF-16, so don't ask.Note that this does not affect any pronunciation dictionary you might currently be using in conjunction with this N-Gram model, so the effect of calling this during decoding is undefined. That's a bug!
int ngram_model_apply_weights(ngram_model_t *model, float32 lw, float32 wip, float32 uw)
Apply a language weight, insertion penalty, and unigram weight to a language model.
This will change the values output by ngram_score() and friends. This is done for efficiency since in decoding, these are the only values we actually need. Call ngram_prob() if you want the "raw" N-Gram probability estimate.To remove all weighting, call ngram_apply_weights(model, 1.0, 1.0, 1.0).
References ngram_model_s::funcs, ngram_funcs_s::apply_weights.
Referenced by ngram_model_read.
float32 ngram_model_get_weights(ngram_model_t *model, int32 *out_log_wip, int32 *out_log_uw)
Get the current weights from a language model.
model The model in question. out_log_wip Output: (optional) logarithm of word insertion penalty. out_log_uw Output: (optional) logarithm of unigram weight. language weight.
References ngram_model_s::log_wip, ngram_model_s::log_uw, ngram_model_s::lw.
int32 ngram_ng_score(ngram_model_t *model, int32 wid, int32 *history, int32 n_hist, int32 *n_used)
Quick general N-Gram score lookup.
References NGRAM_INVALID_WID, ngram_model_s::log_zero, ngram_model_s::classes, ngram_class_s::tag_wid, ngram_model_s::funcs, ngram_funcs_s::score.
Referenced by ngram_score, ngram_tg_score, ngram_bg_score.
int32 ngram_score(ngram_model_t *model, const char *word,...)
Get the score (scaled, interpolated log-probability) for a general N-Gram.
The argument list consists of the history words (as null-terminated strings) of the N-Gram, in reverse order, followed by NULL. Therefore, if you wanted to get the N-Gram score for "a whole joy", you would call: score = ngram_score(model, "joy", "whole", "a", NULL); This is not the function to use in decoding, because it has some overhead for looking up words. Use ngram_ng_score(), ngram_tg_score(), or ngram_bg_score() instead. In the future there will probably be a version that takes a general language model state object, to support suffix-array LM and things like that.If one of the words is not in the LM's vocabulary, the result will depend on whether this is an open or closed vocabulary language model. For an open-vocabulary model, unknown words are all mapped to the unigram <UNK> which has a non-zero probability and also participates in higher-order N-Grams. Therefore, you will get a score of some sort in this case.For a closed-vocabulary model, unknown words are impossible and thus have zero probability. Therefore, if word is unknown, this function will return a "zero" log-probability, i.e. a large negative number. To obtain this number for comparison, call ngram_zero().
References ckd_calloc, ngram_wid, ngram_ng_score, ckd_free.
int32 ngram_tg_score(ngram_model_t *model, int32 w3, int32 w2, int32 w1, int32 *n_used)
Quick trigram score lookup.
References ngram_ng_score.
int32 ngram_bg_score(ngram_model_t *model, int32 w2, int32 w1, int32 *n_used)
Quick bigram score lookup.
References ngram_ng_score.
int32 ngram_ng_prob(ngram_model_t *model, int32 wid, int32 *history, int32 n_hist, int32 *n_used)
Quick "raw" probability lookup for a general N-Gram.
See documentation for ngram_ng_score() and ngram_apply_weights() for an explanation of this.
References NGRAM_INVALID_WID, ngram_model_s::log_zero, ngram_model_s::classes, ngram_class_s::tag_wid, ngram_model_s::funcs, ngram_funcs_s::raw_score.
Referenced by ngram_probv, ngram_prob.
int32 ngram_probv(ngram_model_t *model, const char *word,...)
Get the "raw" log-probability for a general N-Gram.
This returns the log-probability of an N-Gram, as defined in the language model file, before any language weighting, interpolation, or insertion penalty has been applied.When backing off to a unigram from a bigram or trigram, the unigram weight (interpolation with uniform) is not removed.
References ckd_calloc, ngram_wid, ngram_ng_prob, ckd_free.
int32 ngram_prob(ngram_model_t *model, const char *const *words, size_t n)
Get the "raw" log-probability for a general N-Gram.
This returns the log-probability of an N-Gram, as defined in the language model file, before any language weighting, interpolation, or insertion penalty has been applied.When backing off to a unigram from a bigram or trigram, the unigram weight (interpolation with uniform) is not removed.
References ckd_calloc, ngram_wid, ngram_ng_prob, ckd_free.
int32 ngram_score_to_prob(ngram_model_t *base, int32 score)
Convert score to "raw" log-probability.
The unigram weight (interpolation with uniform) is not removed, since there is no way to know which order of N-Gram generated score. model The N-Gram model from which score was obtained. score The N-Gram score to convert The raw log-probability value.
References ngram_model_s::log_wip, ngram_model_s::lw.
int32 ngram_unknown_wid(ngram_model_t *model)
Get the unknown word ID for a language model.
Language models can be either "open vocabulary" or "closed vocabulary". The difference is that the former assigns a fixed non-zero unigram probability to unknown words, while the latter does not allow unknown words (or, equivalently, it assigns them zero probability). If this is a closed vocabulary model, this function will return NGRAM_INVALID_WID.The ID for the unknown word, or NGRAM_INVALID_WID if none exists.
References hash_table_lookup_int32, ngram_model_s::wid, NGRAM_INVALID_WID.
Referenced by ngram_wid, ngram_model_add_class, ngram_model_set_known_wid.
int32 ngram_zero(ngram_model_t *model)
Get the "zero" log-probability value for a language model.
References ngram_model_s::log_zero.
int32 ngram_model_get_size(ngram_model_t *model)
Get the order of the N-gram model (i.e.
the "N" in "N-gram")
References ngram_model_s::n.
int32 const* ngram_model_get_counts(ngram_model_t *model)
Get the counts of the various N-grams in the model.
References ngram_model_s::n_counts.
void ngram_iter_init(ngram_iter_t *itor, ngram_model_t *model, int m, int successor)
Initialize base M-Gram iterator structure.
ngram_iter_t* ngram_model_mgrams(ngram_model_t *model, int m)
Iterate over all M-grams.
model Language model to query. m Order of the M-Grams requested minus one (i.e. order of the history) An iterator over the requested M, or NULL if no N-grams of order M+1 exist.
References ngram_model_s::n, ngram_model_s::funcs, ngram_funcs_s::mgrams.
ngram_iter_t* ngram_iter(ngram_model_t *model, const char *word,...)
Get an iterator over M-grams pointing to the specified M-gram.
References ckd_calloc, ngram_wid, ngram_ng_iter, ckd_free.
ngram_iter_t* ngram_ng_iter(ngram_model_t *model, int32 wid, int32 *history, int32 n_hist)
Get an iterator over M-grams pointing to the specified M-gram.
References ngram_model_s::n, ngram_model_s::funcs, ngram_funcs_s::iter.
Referenced by ngram_iter.
ngram_iter_t* ngram_iter_successors(ngram_iter_t *itor)
Iterate over all M-gram successors of an M-1-gram.
itor Iterator pointing to the M-1-gram to get successors of.
References ngram_iter_s::m, ngram_model_s::n, ngram_model_s::funcs, ngram_funcs_s::successors.
int32 const* ngram_iter_get(ngram_iter_t *itor, int32 *out_score, int32 *out_bowt)
Get information from the current M-gram in an iterator.
out_score Output: Score for this M-gram (including any word penalty and language weight). out_bowt Output: Backoff weight for this M-gram. read-only array of word IDs.
References ngram_model_s::funcs, ngram_funcs_s::iter_get.
ngram_iter_t* ngram_iter_next(ngram_iter_t *itor)
Advance an M-gram iterator.
References ngram_model_s::funcs, ngram_funcs_s::iter_next.
void ngram_iter_free(ngram_iter_t *itor)
Terminate an M-gram iterator.
References ckd_free, ngram_iter_s::wids, ngram_model_s::funcs, ngram_funcs_s::iter_free.
int32 ngram_wid(ngram_model_t *model, const char *word)
Look up numerical word ID.
References hash_table_lookup_int32, ngram_model_s::wid, ngram_unknown_wid.
Referenced by ngram_score, ngram_probv, ngram_prob, ngram_iter, ngram_model_add_class_word, ngram_model_add_class, ngram_model_set_add, ngram_model_set_map_words.
const char* ngram_word(ngram_model_t *model, int32 wid)
Look up word string for numerical word ID.
References ngram_model_s::n_words, ngram_model_s::word_str.
int32 ngram_add_word_internal(ngram_model_t *model, const char *word, int32 classid)
Add a word to the word string and ID mapping.
int32 ngram_model_add_word(ngram_model_t *model, const char *word, float32 weight)
Add a word (unigram) to the language model.
The semantics of this are not particularly well-defined for model sets, and may be subject to change. Currently this will add the word to all of the submodels model The model to add a word to. word Text of the word to add. weight Weight of this word relative to the uniform distribution. The word ID for the new word.
References ngram_model_s::log_zero, ngram_model_s::writable, E_WARN, NGRAM_INVALID_WID, ngram_model_s::funcs, ngram_funcs_s::add_ug, logmath_log, ngram_model_s::lmath.
Referenced by ngram_model_add_class.
ngram_class_t* ngram_class_new(ngram_model_t *model, int32 tag_wid, int32 start_wid, glist_t classwords)
Allocate and initialize an N-Gram class.
int32 ngram_class_add_word(ngram_class_t *lmclass, int32 wid, int32 lweight)
void ngram_class_free(ngram_class_t *lmclass)
Deallocate an N-Gram class.
int32 ngram_model_add_class_word(ngram_model_t *model, const char *classname, const char *word, float32 weight)
Add a word to a class in a language model.
model The model to add a word to. classname Name of the class to add this word to. word Text of the word to add. weight Weight of this word relative to the within-class uniform distribution. The word ID for the new word.
References ngram_wid, NGRAM_INVALID_WID, E_ERROR, ngram_model_s::n_classes, ngram_model_s::classes, ngram_class_s::tag_wid, ngram_class_s::n_words, ngram_class_s::n_hash_inuse, logmath_log, ngram_model_s::lmath, ngram_class_s::prob1, ngram_class_s::n_hash, ngram_class_s::ngram_hash_s::wid, ngram_class_s::ngram_hash_s::prob1.
int32 ngram_model_add_class(ngram_model_t *model, const char *classname, float32 classweight, char **words, const float32 *weights, int32 n_words)
Add a new class to a language model.
If classname already exists in the unigram set for model, then it will be converted to a class tag, and classweight will be ignored. Otherwise, a new unigram will be created as in ngram_model_add_word().
References ngram_wid, ngram_unknown_wid, ngram_model_add_word, NGRAM_INVALID_WID, ngram_model_s::n_classes, E_ERROR, glist_add_float32, glist_reverse, glist_free, ngram_model_s::classes, ckd_calloc, ckd_realloc.
Referenced by ngram_model_read_classdef, ngram_model_set_read.
int32 ngram_class_prob(ngram_class_t *lmclass, int32 wid)
Get the in-class log probability for a word in an N-Gram class.
This probability, or 1 if word not found.
int32 read_classdef_file(hash_table_t *classes, const char *file_name)
Read a probdef file.
void classdef_free(classdef_t *classdef)
Free a class definition.
int32 ngram_model_read_classdef(ngram_model_t *model, const char *file_name)
Read a class definition file and add classes to a language model.
This function assumes that the class tags have already been defined as unigrams in the language model. All words in the class definition will be added to the vocabulary as special in-class words. For this reason is is necessary that they not have the same names as any words in the general unigram distribution. The convention is to suffix them with ":class_tag", where class_tag is the class tag minus the enclosing square brackets.0 for success, <0 for error
References hash_table_new, hash_table_free, hash_table_tolist, gnode_ptr, hash_entry_s::val, ngram_model_add_class, ckd_free, glist_free.