pio.c
EXEEXT
FREAD_RETRY_COUNT
STAT_RETRY_COUNT
@5
static void guess_comptype(char const *file, int32 *ispipe, int32 *isgz)
FILE* fopen_comp(const char *file, const char *mode, int32 *ispipe)
In: File to be opened
References E_FATAL, string_join, E_ERROR_SYSTEM, ckd_free, E_ERROR.
Referenced by fopen_compchk.
void fclose_comp(FILE *fp, int32 ispipe)
In: File pointer to be closed
FILE* fopen_compchk(const char *file, int32 *ispipe)
In: File to be opened
References fopen_comp, ckd_calloc, E_WARN, ckd_free.
lineiter_t* lineiter_start(FILE *fh)
Start reading lines from a file.
References ckd_calloc, ckd_malloc, lineiter_next.
Referenced by lineiter_start_clean.
lineiter_t* lineiter_start_clean(FILE *fh)
Start reading lines from a file, skip comments and trim lines.
References lineiter_start, lineiter_next, string_trim, STRING_BOTH.
static lineiter_t* lineiter_next_plain(lineiter_t *li)
lineiter_t* lineiter_next(lineiter_t *li)
Move to the next line in the file.
References string_trim, STRING_BOTH.
Referenced by lineiter_start, lineiter_start_clean.
int lineiter_lineno(lineiter_t *li)
Returns current line number.
void lineiter_free(lineiter_t *li)
Stop reading lines from a file.
References ckd_free.
char* fread_line(FILE *stream, size_t *out_len)
Read a line of arbitrary length from a file and return it as a newly allocated string.
DeprecatedUse line iterators instead. stream The file handle to read from. out_len Output: if not NULL, length of the string read. allocated string containing the line, or NULL on error or EOF.
References ckd_malloc, ckd_realloc.
Referenced by huff_code_read.
int32 fread_retry(void *pointer, int32 size, int32 num_items, FILE *stream)
NFS file reads seem to fail now and then.
Use the following functions in place of the regular fread. It retries failed freads several times and quits only if all of them fail. Be aware, however, that even normal failures such as attempting to read beyond EOF will trigger such retries, wasting about a minute in retries. Arguments identical to regular fread.
References E_ERROR_SYSTEM.
int32 stat_retry(const char *file, struct stat *statbuf)
There is no bitstream decoder, because a stream abstraction is too slow.
Instead we read blocks of bits and treat them as bitvectors. Like fread_retry, but for stat. Arguments identical to regular stat. Return value: 0 if successful, -1 if stat failed several attempts.
References E_ERROR_SYSTEM.
Referenced by stat_mtime.
int32 stat_mtime(const char *file)
Return time of last modification for the given file, or -1 if stat fails.
References stat_retry.
bit_encode_t* bit_encode_attach(FILE *outfh)
Attach bitstream encoder to a file.
References ckd_calloc.
Referenced by huff_code_attach.
bit_encode_t* bit_encode_retain(bit_encode_t *be)
Retain pointer to a bit encoder.
int bit_encode_free(bit_encode_t *be)
Release pointer to a bit encoder.
Note that this does NOT flush any leftover bits.
References ckd_free.
Referenced by huff_code_detach.
int bit_encode_write(bit_encode_t *be, unsigned char const *bits, int nbits)
Write bits to encoder.
Referenced by bit_encode_write_cw.
int bit_encode_write_cw(bit_encode_t *be, uint32 codeword, int nbits)
Write lowest-order bits of codeword to encoder.
References bit_encode_write.
Referenced by huff_code_encode_int, huff_code_encode_str.
int bit_encode_flush(bit_encode_t *be)
Flush any unwritten bits, zero-padding if necessary.
Referenced by huff_code_detach.
int build_directory(const char *path)
Create a directory and all of its parent directories, as needed.
0 on success, <0 on failure.
References E_ERROR.