strfuncs.c
double sb_strtod(const char *s00, char **se)
double atof_c(char const *str)
Locale independent version of atof().
This function behaves like atof() in the "C" locale. Switching locale in a threaded program is extremely uncool, therefore we need this since we pass floats as strings in 1000 different places.
Referenced by logmath_read.
char* string_join(const char *base,...)
Concatenate a NULL-terminated argument list of strings, returning a newly allocated string.
References ckd_calloc.
Referenced by ngram_model_set_read, fopen_comp.
char* string_trim(char *string, enum string_edge_e which)
Remove whitespace from a string, modifying it in-place.
string string to trim, contents will be modified. which one of STRING_START, STRING_END, or STRING_BOTH.
References STRING_START, STRING_BOTH, STRING_END.
Referenced by lineiter_start_clean, lineiter_next.
int32 str2words(char *line, char **ptr, int32 max_ptr)
In/Out: line to be parsed. This string will be modified! (NUL characters inserted at word boundaries)
A word is a string with no whitespace chars in it. Note that the string line is modified as a result: NULL chars are placed after every word in the line. Return value: No. of words found; -1 if no. of words in line exceeds n_wptr.
int32 nextword(char *line, const char *delim, char **word, char *delimfound)
Input: String being searched for next word. Will be modified by this function (NUL characters inserted)
See arguments below. Length of word returned, or -1 if nothing found. This allows you to scan through a line: while ((n = nextword(line, delim, &word, &delimfound)) >= 0) { ... do something with word .. word[n] = delimfound; line = word + n; }