DECODER_STATE_CREATED   = 0
DECODER_STATE_READY     = 1
DECODER_STATE_LISTENING = 2
DECODER_STATE_DECODING  = 3

SUCCESS_OK              = 200

ERROR_GENERIC           = 400
ERROR_CONTROL_MESSAGE   = 422
ERROR_INVALID_CONFIG    = 403
ERROR_NOT_A_FIFO        = 424
ERROR_TIMED_OUT         = 408

WARN_GENERIC            = 800
WARN_RESET              = 810

